### ISSUE TITLE
Quote appear as HTML format: &#039;

### ISSUE THREAD

**Issue by jinformatique** [firefly-iii/firefly-iii#1027]
I am running Firefly III version 4.6.10

#### Description of my issue:

In French Translation, on the home page, the quotes appears like this:
`Il n&#039;y a pas assez d&#039;informations (pour le moment) pour générer ce graphique.`

Context: `array['no_data_for_chart']`
English Text: `There is not enough information (yet) to generate this chart.`

**Comment by JC5** [comment]
I bet there will be more places where this happens. Thanks for letting me know, I’ll get it fixed!

**Comment by JC5** [comment]
This should be fixed in the current version, v4.6.11.

**Comment by jinformatique** [comment]
Hello, 

Thanks for correcting it on the home page. By the way it still happens on the date selector at the top. Here is a screenshot.
![image](https://user-images.githubusercontent.com/487038/33799337-b93da686-dd29-11e7-8cc7-ac45a4dc93c7.png)

To make sure, I updated from 4.6.11 to 4.6.11.1 as it was like on the screenshot, I made a clear reinstallation and it's the same. I cleared my cache browser and tried in Firefox and Chromium.

Cheers.

**Comment by JC5** [comment]
I see some characters work, and other do not. I suspect that somehow the file encoding is off. I can't replicate this on the [demo site](https://firefly-iii.nder.be/), but the fact that it is happening on a clean installation is worrying me.

I can't replicate it though. Could you run this on the command line, to see what comes back?

```
locale -a | grep fr
```

**Comment by jinformatique** [comment]
```
locale -a | grep fr
fran�ais
fr_BE
fr_BE@euro
fr_BE.iso88591
fr_BE.iso885915@euro
fr_BE.utf8
fr_CA
fr_CA.iso88591
fr_CA.utf8
fr_CH
fr_CH.iso88591
fr_CH.utf8
french
fr_FR
fr_FR@euro
fr_FR.iso88591
fr_FR.iso885915@euro
fr_FR.utf8
fr_LU
fr_LU@euro
fr_LU.iso88591
fr_LU.iso885915@euro
fr_LU.utf8
```

I also installed it on my laptop (KDE Neon with LAMP) and there it's fine ! It seems odd.

**Comment by jinformatique** [comment]
Maybe something related:
I made a backup from my shared hosting to my local installation (laptop), 

In french on shared hosting:
![image](https://user-images.githubusercontent.com/487038/33801055-fd868c66-dd4e-11e7-8362-8808a2719caf.png)


In english on shared hosting (many things are missing) :
![image](https://user-images.githubusercontent.com/487038/33801079-7f8f8e6a-dd4f-11e7-9400-337b2acca697.png)


And on my laptop LAMP, everything is fine and graphics are well filled up. Here is my locale on my laptop.
```
locale -a | grep fr
fr_FR.utf8

```

Should I contact my shared hosting support team to ask to change this? What command could I run to make a change?
Shared hosting is running on Linux kernel 2.6.32!

**Comment by JC5** [comment]
The empty chart is a bug in 4.6.11 I think, it should be fixed in the latest version. It will severely break the index and there is little the shared hosting can do.

It could be that the shared hosting is sending back the file as ISO-88591 and not as UTF-8. Could you verify this? In Chrome, check out the response headers for any page request.

**Comment by jinformatique** [comment]
Ok so this is my response headers for /public/ it seems UTF-8 not ISO-88591.

Request URL:https://<mydomain>.net/firefly-iii/public/
Request Method:GET
Status Code:200 
Remote Address:<IP>:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
cache-control:private, must-revalidate
content-encoding:gzip
content-type:text/html; charset=UTF-8
date:Sun, 10 Dec 2017 22:00:11 GMT
expires:-1
pragma:no-cache
server:nginx
status:200
vary:Accept-Encoding
x-microcachable:0
x-powered-by:PHP/7.1.12
