### ISSUE TITLE
Can't open transaction after assigning a tag to it

### ISSUE THREAD

**Issue by zynexiz** [firefly-iii/firefly-iii#10833]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I just noticed that after I assigned a tag to a transaction it trows an error when trying to open it. I can still edit the transaction, but not open it. It seems that this affects every transaction I have added a tag to. Removing the tag from the transaction will remove this error, it's only present when a tag is added.

The error that's thrown is (some parts in Swdish);

```
Firefly III - 500 Internal Server Error :(
Hoppsan! Ett fel uppstod.

Oturligt nog har ett återkalligt fel skett :(. Firefly III har gått sönder. Felet är:

An exception has been thrown during the rendering of a template ("Missing required parameter for [Route: tags.show] [URI: tags/show/{tagOrId}/{start_date?}/{end_date?}] [Missing parameter: tagOrId].") in "/srv/http/firefly-iii/resources/views/transactions/show.twig" at line 418.

This error occurred in file /srv/http/firefly-iii/resources/views/transactions/show.twig on line 418 with code 0.
```

I'm not sure if this bug was present earlier, but it is in version 6.3.2 that I currently is on.

### Debug information

Debug information generated at 2025-08-30 13:26:55 for Firefly III version **v6.3.2**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.3.2 / <span>#</span>26 (expects <span>#</span>26)</td></tr><tr><td>PHP version</td><td>8.4.11 (64bits) / cgi-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>0 (0 KB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Stockholm + Atlantic/Reykjavik</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver, session driver</td><td>file, file</td></tr><tr><td>Default language and locale</td><td>sv_SE + equal</td></tr><tr><td>Trusted proxies</td><td><code></code></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2025-09-08 22:00:00 (1 week from now)</td></tr><tr><td>Mailer</td><td>smtp</td></tr><tr><td>Exchange rates</td><td>Disabled, downloads disabled</td></tr><tr><td>RB-column</td><td>Disabled</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Primary currency</td><td>SEK</td></tr><tr><td>Convert to primary currency?</td><td>Disabled</td></tr><tr><td>Session start</td><td>2025-08-01 00:00:00</td></tr><tr><td>Session end</td><td>2025-08-30 23:59:59</td></tr><tr><td>View range</td><td>MTD</td></tr><tr><td>User language</td><td>sv_SE</td></tr><tr><td>User locale</td><td>sv_SE</td></tr><tr><td>Locale(s) supported</td><td>sv_SE.utf8: :white_check_mark:<br>sv_SE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0</td></tr></tbody></table>

### Steps to reproduce

1. Assign a tag to a transaction
2. Try open the transaction from any page (by clicking on the transaction title)
3. En error page will be shown.
4. Remove the tag and try again, now it will work again.

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

I can't seem to replicate this issue, sorry about that. Also, in Firefly III v6.3.2 line 418 does not cal that route, it does something else entirely. Could you tell me a little bit more about your setup?

Cheers,
James

**Comment by zynexiz** [comment]
Hey,

That's a bit odd, when I removed the tag it worked again so something is causing it. I'm running it on Arch Linux with Apache inside a VM. Don't have any real odd solution running, think this worked a while back though. I'll add a show video clip what's happening, not sure if that helps.

https://github.com/user-attachments/assets/73788b8d-26c9-4fee-bf0b-26b3dd0a39a4

**Comment by zynexiz** [comment]
Noticed I forgot to add the content from the error mail I got when this happened.

```
#0 /srv/http/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(94): TwigBridge\Engine\Twig->handleTwigError()
#1 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(208): TwigBridge\Engine\Twig->get()
#2 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(191): Illuminate\View\View->getContents()
#3 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(160): Illuminate\View\View->renderContents()
#4 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Http/Response.php(78): Illuminate\View\View->render()
#5 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\Http\Response->setContent()
#6 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(939): Illuminate\Http\Response->__construct()
#7 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(906): Illuminate\Routing\Router::toResponse()
#8 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(821): Illuminate\Routing\Router->prepareResponse()
#9 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Router->{closure:Illuminate\Routing\Router::runRouteWithinStack():821}()
#10 /srv/http/firefly-iii/app/Http/Controllers/Transaction/ShowController.php(67): Illuminate\Pipeline\Pipeline->{closure:Illuminate\Pipeline\Pipeline::prepareDestination():178}()
#11 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(201): FireflyIII\Http\Controllers\Transaction\ShowController->{closure:FireflyIII\Http\Controllers\Transaction\ShowController::__construct():60}()
#12 /srv/http/firefly-iii/app/Http/Controllers/Controller.php(157): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#13 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(201): FireflyIII\Http\Controllers\Controller->{closure:FireflyIII\Http\Controllers\Controller::__construct():123}()
#14 /srv/http/firefly-iii/app/Http/Middleware/InterestingMessage.php(80): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#15 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): FireflyIII\Http\Middleware\InterestingMessage->handle()
#16 /srv/http/firefly-iii/app/Http/Middleware/Binder.php(76): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#17 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): FireflyIII\Http\Middleware\Binder->handle()
#18 /srv/http/firefly-iii/app/Http/Middleware/Range.php(60): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#19 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): FireflyIII\Http\Middleware\Range->handle()
#20 /srv/http/firefly-iii/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#21 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): PragmaRX\Google2FALaravel\Middleware->handle()
#22 /srv/http/firefly-iii/app/Http/Middleware/Authenticate.php(66): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#23 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): FireflyIII\Http\Middleware\Authenticate->handle()
#24 /srv/http/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(63): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#25 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#26 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(66): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#27 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Session\Middleware\AuthenticateSession->handle()
#28 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(87): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#29 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#30 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(48): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#31 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#32 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(120): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#33 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#34 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Session\Middleware\StartSession->handle()
#35 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#36 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#37 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(74): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#38 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#39 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#40 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(821): Illuminate\Pipeline\Pipeline->then()
#41 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\Routing\Router->runRouteWithinStack()
#42 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(764): Illuminate\Routing\Router->runRoute()
#43 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(753): Illuminate\Routing\Router->dispatchToRoute()
#44 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#45 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Kernel->{closure:Illuminate\Foundation\Http\Kernel::dispatchToRouter():197}()
#46 /srv/http/firefly-iii/app/Http/Middleware/InstallationId.php(49): Illuminate\Pipeline\Pipeline->{closure:Illuminate\Pipeline\Pipeline::prepareDestination():178}()
#47 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): FireflyIII\Http\Middleware\InstallationId->handle()
#48 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#49 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Http\Middleware\TrustProxies->handle()
#50 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#51 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#52 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#53 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#54 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#55 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#56 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#57 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Http\Middleware\ValidatePostSize->handle()
#58 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(109): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#59 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#60 /srv/http/firefly-iii/app/Http/Middleware/SecureHeaders.php(55): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#61 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): FireflyIII\Http\Middleware\SecureHeaders->handle()
#62 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Pipeline\Pipeline->{closure:{closure:Illuminate\Pipeline\Pipeline::carry():194}:195}()
#63 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#64 /srv/http/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#65 /srv/http/firefly-iii/public/index.php(78): Illuminate\Foundation\Http\Kernel->handle()
#66 {main}

The following headers may also be relevant:

- content-length: 0
- priority: u=0, i
- sec-fetch-user: ?1
- sec-fetch-site: same-origin
- sec-fetch-mode: navigate
- sec-fetch-dest: document
- upgrade-insecure-requests: 1
- connection: close
- sec-gpc: 1
- dnt: 1
- accept-encoding: gzip, deflate, br, zstd
- accept-language: sv,en;q=0.5
- accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
- user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0
```

**Comment by JC5** [comment]
So again, in Firefly III v6.3.2 there is no code on line 418 of that particular file to error on. Could you tell me how you set up Firefly III? Did you download it, do you upgrade manually, etc?

**Comment by zynexiz** [comment]
Think I deployed it using the install guide on your site (was a while ago now) for the self-managed approach, and manually updates it with a script on my server. It basically automates the update instructions in the manual.

```
#!/bin/bash

# If not user http, run it as that user
if [ $USER != "http" ]; then
  SELF_NAME=`basename $0`
  SELF_PATH=$(dirname $(readlink -f $0))
  sudo -u http "$SELF_PATH/$SELF_NAME"
  exit
fi

# Get latest version of firefly
latestversion=$(curl -s https://api.github.com/repos/firefly-iii/firefly-iii/releases/latest  | grep -oP '"tag_name": "\K(.*)(?=")')
installedversion=`cat /srv/http/firefly-iii/version`


if [ $installedversion == $latestversion ]; then
  echo 'Already latest version ('$installedversion')'
  exit
fi

echo 'Version '$installedversion' installed, new version '$latestversion

# Download and unpack the new version and copy files from old instance
cd /srv/http
echo -n 'Downloading and unpacking Firefly III version '$latestversion'... '
wget -q https://github.com/firefly-iii/firefly-iii/releases/download/$latestversion/FireflyIII-$latestversion.zip
unzip -q -o FireflyIII-$latestversion.zip -d ./firefly-iii-update
cp firefly-iii/.env firefly-iii-update/.env
cp -r firefly-iii/storage ./firefly-iii-update
echo "done."

# Install latest version
cd firefly-iii-update
php artisan migrate --seed
php artisan cache:clear
php artisan view:clear
php artisan firefly-iii:upgrade-database
php artisan firefly-iii:laravel-passport-keys

cd ..
# Remove old version of firefly-iii
if [ -d "firefly-iii-old" ]; then
  rm -r firefly-iii-old
fi

# Serve the new version
mv firefly-iii firefly-iii-old
mv firefly-iii-update firefly-iii
rm FireflyIII-$latestversion.zip

echo $latestversion | tee /srv/http/firefly-iii/version > /dev/null

```

**Comment by drvieira** [comment]
Hi,
I'm having the same issue. I just updated from 6.2.20 to 6.3.2. It was deployed and updated manually using the "Upgrade a self-managed server" instructions.

```
An exception has been thrown during the rendering of a template ("Missing required parameter for [Route: tags.show] [URI: tags/show/{tagOrId}/{start_date?}/{end_date?}] [Missing parameter: tagOrId].") in "/var/www/html/firefly-iii/resources/views/transactions/show.twig" at line 418.

This error occurred in file /var/www/html/firefly-iii/resources/views/transactions/show.twig on line 418 with code 0.
```

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.3.2 / <span>#</span>26 (expects <span>#</span>26)</td></tr><tr><td>PHP version</td><td>8.4.11 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/Sao_Paulo + America/Sao_Paulo</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver, session driver</td><td>redis, redis</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td><code></code></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2025-09-03 06:00:02 (8 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr><tr><td>Exchange rates</td><td>Disabled, downloads disabled</td></tr><tr><td>RB-column</td><td>Disabled</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has reconciled">:ledger:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Native currency</td><td></td></tr><tr><td>Convert to native currency?</td><td>Disabled</td></tr><tr><td>Session start</td><td>2025-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2025-09-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36</td></tr></tbody></table>

**Comment by JC5** [comment]
I'm sorry to hear that. I have a hard time replicating this issue. I may have a fix but honestly I'm going in blind here.

**Comment by zynexiz** [comment]
> I'm sorry to hear that. I have a hard time replicating this issue. I may have a fix but honestly I'm going in blind here.

No worries, I will try out if it's fixed in the next release and report back 😄

**Comment by Ada-CD** [comment]
Hi,
I am also encountering this issue after updating from 6.2.21 to 6.3.2.

I checked with the latest development release and it seems to have fixed it for me, so hopefully it should work for the others as well !

Here is my debug info, in case it might be useful to find a root cause/replicate ?

<hr/>

Debug information generated at 2025-09-08 20:53:01 for Firefly III version **v6.3.2**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.3.2 / <span>#</span>26 (expects <span>#</span>26)</td></tr><tr><td>PHP version</td><td>8.4.11 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td>mysql, <strong>*sqlite*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/London + Europe/London</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver, session driver</td><td>file, file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td><code>**</code></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2025-09-08 05:00:02 (14 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr><tr><td>Exchange rates</td><td>Disabled, downloads disabled</td></tr><tr><td>RB-column</td><td>Disabled</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has reconciled">:ledger:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Primary currency</td><td>GBP</td></tr><tr><td>Convert to primary currency?</td><td>Disabled</td></tr><tr><td>Session start</td><td>2025-09-01 00:00:00</td></tr><tr><td>Session end</td><td>2025-09-30 00:00:00</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>fr_FR</td></tr><tr><td>Locale(s) supported</td><td>fr_FR.utf8: :white_check_mark:<br>fr_FR.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0</td></tr></tbody></table>

**Comment by zeitwidrig** [comment]
Still happening in 6.4.0 😕 (upgraded from 6.2.21 which was the last version that worked for me)

<img width="717" height="295" alt="Image" src="https://github.com/user-attachments/assets/cca04474-74a1-450c-bf6e-be61a4c77f19" />

Transactions without tags show up fine, all other throw this error.

To be honest, some of the earlier tags in the database look a bit rubbish:

<img width="1402" height="356" alt="Image" src="https://github.com/user-attachments/assets/6e12d51f-3471-4660-8a76-848b05a303c4" />

They obviously don't show up in the tag overview but maybe it gets in the way when rendering the template?

**Comment by JC5** [comment]
Could you grab the `show.twig` file you have at that path and share it here?

**Comment by zeitwidrig** [comment]
Sure. Can't attach it, so full copypaste:

```php
{% extends './layout/default' %}

{% block breadcrumbs %}
    {{ Breadcrumbs.render(Route.getCurrentRoute.getName, transactionGroup) }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ 'transaction_journal_information'|_ }}</h3>
                    <div class="btn-group btn-group-xs pull-right">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            {{ 'actions'|_ }} <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            {# edit + delete #}
                            <li><a href="{{ route('transactions.edit', [transactionGroup.id]) }}"><span
                                        class="fa fa-pencil"></span> {{ 'edit'|_ }}</a></li>
                            {% if groupArray.transactions[0].type != 'reconciliation' and groupArray.transactions[0].type != 'opening balance' and groupArray.transactions[0].type != 'liability credit' %}
                            <li><a href="{{ route('transactions.delete', [transactionGroup.id]) }}"><span
                                        class="fa fa-trash"></span> {{ 'delete'|_ }}</a></li>
                            {% endif %}
                            {% if groupArray.transactions[0].type != 'reconciliation' and groupArray.transactions[0].type != 'opening balance' and groupArray.transactions[0].type != 'liability credit' %}
                            <li role="separator" class="divider"></li>

                            {# convert to different type #}
                            {% if groupArray.transactions[0].type != 'withdrawal' %}
                                <li>
                                    <a href="{{ route('transactions.convert.index', ['withdrawal', transactionGroup.id]) }}"><span
                                            class="fa fa-exchange"></span> {{ 'convert_to_withdrawal'|_ }}</a></li>
                            {% endif %}

                            {% if groupArray.transactions[0].type != 'deposit' %}
                                <li>
                                    <a href="{{ route('transactions.convert.index', ['deposit', transactionGroup.id]) }}"><span
                                            class="fa fa-exchange"></span> {{ 'convert_to_deposit'|_ }}</a></li>
                            {% endif %}

                            {% if groupArray.transactions[0].type != 'transfer' %}
                                <li>
                                    <a href="{{ route('transactions.convert.index', ['transfer', transactionGroup.id]) }}"><span
                                            class="fa fa-exchange"></span> {{ 'convert_to_transfer'|_ }}</a></li>
                            {% endif %}


                            {#  clone #}
                            {% if groupArray.transactions[0].type != 'opening balance' and groupArray.transactions[0].type != 'reconciliation' %}
                                <li role="separator" class="divider"></li>
                                <li><a href="#" class="clone-transaction" data-id="{{ transactionGroup.id }}"><span
                                            class="fa fa-copy"></span> {{ 'clone'|_ }}</a></li>
                                <li><a href="#" class="clone-transaction-and-edit" data-id="{{ transactionGroup.id }}"><span
                                            class="fa fa-copy"></span> {{ 'clone_and_edit'|_ }}</a></li>
                            {% endif %}
                            {% endif %}

                        </ul>
                    </div>
                </div>
                <div class="box-body no-padding">
                    <table class="table table-hover">
                        <tbody>
                        <tr>
                            <td style="width:40%;">{{ trans('list.type') }}</td>
                            <td>{{ first.transaction_type_type|_ }}</td>
                        </tr>
                        <tr>
                            <td>{{ trans('list.description') }}</td>
                            <td>
                                {% if splits == 1 %}
                                    {{ first.description }}
                                {% else %}
                                    {{ transactionGroup.title }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td style="width:30%;">{{ trans('list.date') }}</td>
                            <td>
                                <span class="date-time" data-date="{{ first.date.toIso8601ZuluString() }}" title="{{ first.date.isoFormat(dateTimeFormat) }}{% if(first.date_tz != '') %} ({{ trans('firefly.stored_in_tz', {timezone: first.date_tz }) }}, {{ trans('firefly.displayed_in_tz', {timezone: config('app.timezone') }) }}){% endif %}">
                                {{ first.date.isoFormat(dateTimeFormat) }}
                                {% if(first.date_tz != '') %}
                                    ({{ trans('firefly.stored_in_tz', {timezone: first.date_tz }) }})
                                {% endif %}
                                </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            {% if groupLogEntries|length > 0 %}
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">
                            {{ 'audit_log_entries'|_ }}
                        </h3>
                    </div>
                    <div class="box-body no-padding">
                        {% include 'list.ale' with {logEntries: groupLogEntries} %}
                    </div>
                </div>
            {% endif %}

        </div>
        <div class="col-lg-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ 'transaction_journal_meta'|_ }}</h3>
                </div>
                <div class="box-body no-padding">
                    <table class="table table-hover">
                        <tbody>
                        {% if first.transaction_type_type != 'Withdrawal' or splits == 1 %}
                            <tr>
                                <td style="width:40%;">
                                    {{ trans_choice('firefly.source_accounts', accounts['source']|length ) }}
                                </td>
                                <td>
                                    {% for account in accounts['source'] %}
                                        {% if 'Cash account' == account.type %}
                                            <span class="text-success">({{ 'cash'|_ }})</span>
                                        {% else %}
                                            <a href="{{ route('accounts.show',account.id) }}"
                                               title="{{ account.iban|default(account.name) }}">
                                                {{ account.name }}
                                            </a>
                                        {% endif %}
                                        {% if loop.index0 != accounts['source']|length -1 %}, {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}

                        {% if first.transaction_type_type != 'Deposit' or splits == 1 %}
                            <tr>
                                <td>
                                    {{ trans_choice('firefly.destination_accounts', accounts['destination']|length ) }}

                                </td>
                                <td>
                                    {% for account in accounts['destination'] %}
                                        {% if 'Cash account' == account.type %}
                                            <span class="text-success">({{ 'cash'|_ }})</span>
                                        {% else %}
                                            <a href="{{ route('accounts.show',account.id) }}"
                                               title="{{ account.iban|default(account.name) }}">
                                                {{ account.name }}
                                            </a>
                                        {% endif %}
                                        {% if loop.index0 != accounts['destination']|length -1 %}, {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}
                        <tr>
                            <td style="width:30%;">{{ 'total_amount'|_ }}</td>
                            <td>
                                {% for amount in amounts %}
                                    {% if first.transaction_type_type == 'Withdrawal' %}
                                        {{ formatAmountBySymbol(amount.amount,amount.symbol, amount.decimal_places) }}{% if loop.index0 != amounts|length -1 %}, {% endif %}
                                    {% elseif first.transaction_type_type == 'Deposit' %}
                                        {{ formatAmountBySymbol(amount.amount*-1,amount.symbol, amount.decimal_places) }}{% if loop.index0 != amounts|length -1 %}, {% endif %}
                                    {% elseif first.transaction_type_type == 'Transfer' %}
                                        <span class="text-info money-transfer">

                                        {{ formatAmountBySymbol(amount.amount*-1, amount.symbol, amount.decimal_places, false) }}{% if loop.index0 != amounts|length -1 %}, {% endif %}
                                    </span>
                                    {% elseif first.transaction_type_type == 'Opening balance' %}
                                        {# Opening balance stored amount is always negative: find out which way the money goes #}
                                        {% if groupArray.transactions[0].source_account_type == 'Initial balance account' %}
                                            {{ formatAmountBySymbol(amount.amount*-1,amount.symbol, amount.decimal_places) }}
                                        {% else %}
                                            {{ formatAmountBySymbol(amount.amount,amount.symbol, amount.decimal_places) }}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

    </div>
    {% if splits > 1 %}
        <div class="row">
            <div class="col-lg-12">
                <h3>{{ 'splits'|_ }}</h3>
            </div>
        </div>
    {% endif %}
    {% set boxSize=6 %}
    {% if(splits == 2) %}
        {% set boxSize=6 %}
    {% endif %}
    {% if (splits > 2) %}
        {% set boxSize = 4 %}
    {% endif %}
    <div class="row">
        {% for index,journal in selectedGroup.transactions %}
            <div class="col-lg-{{ boxSize }}">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">
                            {{ journal.description }}
                            {% if journal.reconciled %}
                                <span class="fa fa-check"></span>
                            {% endif %}
                            {% if splits > 1 %}
                                <small>
                                    {{ index+1 }} / {{ splits }}
                                </small>
                            {% endif %}
                        </h3>


                        <div class="btn-group btn-group-xs pull-right">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                {{ 'actions'|_ }} <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                {# edit + delete #}
                                <li><a href="{{ route('transactions.edit', [transactionGroup.id]) }}"><span
                                            class="fa fa-pencil"></span> {{ 'edit'|_ }}</a></li>
                                {% if groupArray.transactions[0].type != 'reconciliation' and groupArray.transactions[0].type != 'opening balance' and groupArray.transactions[0].type != 'liability credit' %}
                                <li><a href="{{ route('transactions.delete', [transactionGroup.id]) }}"><span
                                            class="fa fa-trash"></span> {{ 'delete'|_ }}</a></li>
                                {% endif %}
                                {% if journal.reconciled %}
                                <li><a class="reconcile-button" href="{{ route('transactions.unreconcile', [journal.transaction_journal_id]) }}"><span
                                            class="fa fa-history"></span> {{ 'unreconcile'|_ }}</a></li>
                                {% endif %}
                                {% if groupArray.transactions[0].type != 'reconciliation' and groupArray.transactions[0].type != 'opening balance' and groupArray.transactions[0].type != 'liability credit' %}
                                <li role="separator" class="divider"></li>

                                {# convert to different type #}
                                {% if groupArray.transactions[0].type != 'withdrawal' %}
                                    <li>
                                        <a href="{{ route('transactions.convert.index', ['withdrawal', transactionGroup.id]) }}"><span
                                                class="fa fa-exchange"></span> {{ 'convert_to_withdrawal'|_ }}</a>
                                    </li>
                                {% endif %}

                                {% if groupArray.transactions[0].type != 'deposit' %}
                                    <li>
                                        <a href="{{ route('transactions.convert.index', ['deposit', transactionGroup.id]) }}"><span
                                                class="fa fa-exchange"></span> {{ 'convert_to_deposit'|_ }}</a></li>
                                {% endif %}

                                {% if groupArray.transactions[0].type != 'transfer' %}
                                    <li>
                                        <a href="{{ route('transactions.convert.index', ['transfer', transactionGroup.id]) }}"><span
                                                class="fa fa-exchange"></span> {{ 'convert_to_transfer'|_ }}</a>
                                    </li>
                                {% endif %}

                                {#  clone #}
                                {% if groupArray.transactions[0].type != 'opening balance' and groupArray.transactions[0].type != 'reconciliation' %}
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#" data-id="{{ transactionGroup.id }}" class="clone-transaction"><span
                                                class="fa fa-copy"></span> {{ 'clone'|_ }}</a></li>
                                    <li><a href="#" data-id="{{ transactionGroup.id }}" class="clone-transaction-and-edit"><span
                                                class="fa fa-copy"></span> {{ 'clone_and_edit'|_ }}</a></li>
                                {% endif %}

                                <li><a href="#" class="link-modal"
                                       data-journal="{{ journal.transaction_journal_id }}"><span
                                            class="fa fa-fw fa-link"></span>{{ 'link_transaction'|_ }}</a></li>
                                <li role="separator" class="divider"></li>
                                <li>
                                    <a href="{{ route('rules.create-from-journal', [journal.transaction_journal_id]) }}"><span
                                            class="fa fa-fw fa-random"></span>{{ 'create_rule_from_transaction'|_ }}
                                    </a></li>
                                <li>
                                    <a href="{{ route('recurring.create-from-journal', [journal.transaction_journal_id]) }}"><span
                                            class="fa fa-fw fa-paint-brush"></span>{{ 'create_recurring_from_transaction'|_ }}
                                    </a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <table class="table">
                            <tr>
                                <td colspan="2">
                                    {% if 'Cash account' == journal.source_account_type %}
                                        <span class="text-success">({{ 'cash'|_ }})</span>
                                    {% else %}
                                        <a href="{{ route('accounts.show', journal.source_account_id) }}"
                                           title="{{ journal.source_iban|default(journal.source_account_name) }}">{{ journal.source_account_name }}</a> &rarr;
                                    {% endif %}

                                    {% if first.transaction_type_type == 'Withdrawal' %}
                                        {{ formatAmountBySymbol(journal.amount, journal.currency_symbol, journal.currency_decimal_places) }}
                                    {% elseif first.transaction_type_type == 'Deposit' %}
                                        {{ formatAmountBySymbol(journal.amount*-1, journal.currency_symbol, journal.currency_decimal_places) }}
                                    {% elseif first.transaction_type_type == 'Transfer' or first.transaction_type_type == 'Opening balance' %}
                                        <span class="text-info money-transfer">
                                        {{ formatAmountBySymbol(journal.amount*-1, journal.currency_symbol, journal.currency_decimal_places, false) }}
                                    </span>
                                    {% elseif first.transaction_type_type == 'Liability credit' %}
                                        <span class="text-info money-transfer">
                                        {{ formatAmountBySymbol(journal.amount*-1, journal.currency_symbol, journal.currency_decimal_places, false) }}
                                    </span>
                                    {% endif %}

                                    <!-- do primary currency amount -->
                                    {% if null != journal.pc_amount and primaryCurrency.id != journal.currency_id %}
                                        {% if first.transaction_type_type == 'Withdrawal' %}
                                            ({{ formatAmountBySymbol(journal.pc_amount, primaryCurrency.symbol, primaryCurrency.decimal_places) }})
                                        {% elseif first.transaction_type_type == 'Deposit' %}
                                            ({{ formatAmountBySymbol(journal.pc_amount*-1, primaryCurrency.symbol, primaryCurrency.decimal_places) }})
                                        {% elseif first.transaction_type_type == 'Transfer' %}
                                            <span class="text-info money-transfer">
                                        ({{ formatAmountBySymbol(journal.pc_amount*-1, primaryCurrency.symbol, primaryCurrency.decimal_places, false) }})
                                    </span>
                                        {% endif %}
                                    {% endif %}

                                    <!-- do foreign amount -->
                                    {% if null != journal.foreign_amount %}
                                        {% if first.transaction_type_type == 'Withdrawal' %}
                                            ({{ formatAmountBySymbol(journal.foreign_amount, journal.foreign_currency_symbol, journal.foreign_currency_decimal_places) }})
                                        {% elseif first.transaction_type_type == 'Deposit' %}
                                            ({{ formatAmountBySymbol(journal.foreign_amount*-1, journal.foreign_currency_symbol, journal.foreign_currency_decimal_places) }})
                                        {% elseif first.transaction_type_type == 'Transfer' %}
                                            <span class="text-info money-transfer">
                                        ({{ formatAmountBySymbol(journal.foreign_amount*-1, journal.foreign_currency_symbol, journal.foreign_currency_decimal_places, false) }})
                                    </span>
                                        {% endif %}
                                    {% endif %}

                                    <!-- do foreign PC amount -->
                                    {% if null != journal.pc_foreign_amount %}
                                        {% if first.transaction_type_type == 'Withdrawal' %}
                                            ({{ formatAmountBySymbol(journal.pc_foreign_amount, primaryCurrency.symbol, primaryCurrency.decimal_places) }})
                                        {% elseif first.transaction_type_type == 'Deposit' %}
                                            ({{ formatAmountBySymbol(journal.pc_foreign_amount*-1, primaryCurrency.symbol, primaryCurrency.decimal_places) }})
                                        {% elseif first.transaction_type_type == 'Transfer' %}
                                            <span class="text-info money-transfer">
                                        ({{ formatAmountBySymbol(journal.pc_foreign_amount*-1, primaryCurrency.symbol, primaryCurrency.decimal_places, false) }})
                                    </span>
                                        {% endif %}
                                    {% endif %}


                                    &rarr;
                                    {% if 'Cash account' == journal.destination_account_type %}
                                        <span class="text-success">({{ 'cash'|_ }})</span>
                                    {% else %}
                                        <a href="{{ route('accounts.show', journal.destination_account_id) }}"
                                           title="{{ journal.destination_iban|default(journal.destination_account_name) }}">{{ journal.destination_account_name }}</a>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>{{ 'transaction_journal_id'|_ }}</td>
                                <td>#{{ journal.transaction_journal_id }}</td>
                            </tr>
                            {% if null != journal.category_id %}
                                <tr>
                                    <td style="width:30%;">{{ 'category'|_ }}</td>
                                    <td>
                                        <a href="{{ route('categories.show', [journal.category_id]) }}">{{ journal.category_name }}</a>
                                    </td>
                                </tr>
                            {% endif %}
                            {% if null != journal.budget_id and first.transaction_type_type == 'Withdrawal' %}
                                <tr>
                                    <td style="width:40%;">{{ 'budget'|_ }}</td>
                                    <td>
                                        <a href="{{ route('budgets.show', [journal.budget_id]) }}">{{ journal.budget_name }}</a>
                                    </td>
                                </tr>
                            {% endif %}
                            {% if null != journal.bill_id and first.transaction_type_type == 'Withdrawal' %}
                                <tr>
                                    <td style="width:40%;">{{ 'bill'|_ }}</td>
                                    <td>
                                        <a href="{{ route('subscriptions.show', [journal.bill_id]) }}">{{ journal.bill_name }}</a>
                                    </td>
                                </tr>
                            {% endif %}
                            <!-- other fields -->
                            {% for dateField in ['interest_date','book_date','process_date','due_date','payment_date','invoice_date'] %}
                                {% if journalHasMeta(journal.transaction_journal_id, dateField) %}
                                    <tr>
                                        <td style="width:40%;">{{ trans('list.'~dateField) }}</td>
                                        <td>{{ journalGetMetaDate(journal.transaction_journal_id, dateField).isoFormat(monthAndDayFormat) }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            {% for metaField in ['external_id','bunq_payment_id','internal_reference','sepa_batch_id','sepa_ct_id','sepa_ct_op','sepa_db','sepa_country','sepa_cc','sepa_ep','sepa_ci','external_url'] %}
                                {% if journalHasMeta(journal.transaction_journal_id, metaField) %}
                                    <tr>
                                        <td>{{ trans('list.'~metaField) }}</td>
                                        <td style="width:40%;">
                                            {% if 'external_url' == metaField %}
                                                {% set url = journalGetMetaField(journal.transaction_journal_id, metaField) %}
                                                <a href="{{ url }}" rel="noopener noreferrer nofollow" target="_blank">
                                                    {% if url|length > 60 %}
                                                        {{ url|slice(0, 60) ~ '...' }}
                                                    {% else %}
                                                        {{ url }}
                                                    {% endif %}
                                                </a>
                                            {% endif %}
                                            {% if 'external_url' != metaField %}
                                                {{ journalGetMetaField(journal.transaction_journal_id, metaField) }}
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            {% if null != journal.notes and '' != journal.notes %}
                                <tr>
                                    <td style="width:40%;">{{ trans('list.notes') }}</td>
                                    <td class="markdown">{{ journal.notes|default('')|markdown }}</td>
                                </tr>
                            {% endif %}
                            {% if journalHasMeta(journal.transaction_journal_id, 'recurring_total') and journalHasMeta(journal.transaction_journal_id, 'recurring_count') %}
                                {% set recurringTotal = journalGetMetaField(journal.transaction_journal_id, 'recurring_total') %}
                                {% if 0 == recurringTotal %}
                                    {% set recurringTotal = '∞' %}
                                {% endif %}
                                <tr>
                                    <td style="width:40%;">{{ trans('list.recurring_transaction') }}</td>
                                    <td>{{ trans('firefly.recurring_info', {total: recurringTotal, count: journalGetMetaField(journal.transaction_journal_id, 'recurring_count') }) }}</td>
                                </tr>
                            {% endif %}
                            {% if journal.tags|length > 0 %}
                                <tr>
                                    <td style="width:40%;">{{ 'tags'|_ }}</td>
                                    <td>
                                        {% for tag in journal.tags %}
                                            {% if null != tag.id %}
                                                <h4 style="display: inline;"><a class="label label-success" href="{{ route('tags.show', [tag.id]) }}"><span class="fa fa-fw fa-tag"></span>{{ tag.tag }}</a></h4>
                                            {% endif %}
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endif %}
                        </table>
                    </div>
                </div>

                <!-- Transaction links -->
                {% if links[journal.transaction_journal_id]|length > 0 %}
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">
                                {{ 'journal_links'|_ }}
                            </h3>
                        </div>
                        <div class="box-body no-padding">
                            <table class="table">
                                {% for link in links[journal.transaction_journal_id] %}
                                    <tr>
                                        <td style="width:120px;">
                                            <div class="btn-group btn-group-xs">
                                                <a href="#" class="btn btn-default switch-link" data-id="{{ link.id }}"><span
                                                        class="fa fa-fw fa-arrows-h"></span></a>
                                                <a href="{{ route('transactions.link.delete', [link.id]) }}"
                                                   class="btn btn-danger"><span class="fa fa-trash"></span></a>
                                            </div>
                                        </td>
                                        <td>
                                            {% if link.editable %}
                                                {{ link.link }}
                                            {% else %}
                                                {{ trans('firefly.'~link.link) }}
                                            {% endif %}
                                            "<a href="{{ route('transactions.show', link.group) }}"
                                                title="{{ link.description }}">{{ link.description }}</a>"

                                            ({{ link.amount|raw }})
                                            {% if '' != link.foreign_amount %}
                                                ({{ link.foreign_amount|raw }})
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}

                            </table>
                        </div>
                    </div>
                {% endif %}

                <!-- Attachments -->
                {% if attachments[journal.transaction_journal_id]|length > 0 %}
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">{{ 'attachments'|_ }}</h3>
                        </div>
                        <div class="box-body no-padding">
                            {% include 'list.attachments' with {attachments: attachments[journal.transaction_journal_id]} %}
                        </div>
                    </div>
                {% endif %}

                <!-- Piggy bank events -->
                {% if events[journal.transaction_journal_id]|length > 0 %}
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">{{ 'piggy_events'|_ }}</h3>
                        </div>
                        <div class="box-body no-padding">
                            <table class="table table-hover">
                                {% for event in events[journal.transaction_journal_id] %}
                                    <tr>
                                        <td style="width:30%;">{{ event.amount|raw }}</td>
                                        <td>
                                            <a href="{{ route('piggy-banks.show', [event.piggy_id]) }}">{{ event.piggy }}</a>
                                        </td>

                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                {% endif %}
                {% if logEntries[journal.transaction_journal_id]|length > 0 %}
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">
                                {{ 'audit_log_entries'|_ }}
                            </h3>
                        </div>
                        <div class="box-body no-padding">
                            {% include 'list.ale' with {logEntries: logEntries[journal.transaction_journal_id]} %}
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    {# modal for linking journals. Will be filled by AJAX #}
    <div class="modal fade" tabindex="-1" role="dialog" id="linkJournalModal">
    </div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" nonce="{{ JS_NONCE }}">
        var modalDialogURL = '{{ route('transactions.link.modal', ['%JOURNAL%']) }}';
        var acURL = '{{ route('api.v1.autocomplete.transactions-with-id') }}';
        var groupURL = '{{ route('transactions.show',['%GROUP%']) }}';
        var cloneGroupUrl = '{{ route('transactions.clone') }}';
        var cloneAndEditUrl = '{{ route('transactions.clone') }}?redirect=edit';


        $('.switch-link').on('click', switchLink);
        $('.reconcile-button').on('click', unreconcile);
        var switchLinkUrl = '{{ route('transactions.link.switch') }}';

        function unreconcile(e) {
            e.preventDefault();
            var obj = $(e.currentTarget);
            $.post(obj.attr('href'), {
                _token: token
            }).done(function () {
                location.reload();
            }).fail(function () {
                console.error('I failed :(');
            });

            return false
        }

        function switchLink(e) {
            e.preventDefault();
            var obj = $(e.currentTarget);
            $.post(switchLinkUrl, {
                _token: token,
                id: obj.data('id')
            }).done(function () {
                location.reload();
            }).fail(function () {
                console.error('I failed :(');
            });

            //alert(obj.data('id'));

            return false
        }
    </script>
    <script type="text/javascript" src="v1/js/lib/typeahead/typeahead.bundle.min.js?v={{ FF_VERSION }}"
            nonce="{{ JS_NONCE }}"></script>
    <script type="text/javascript" src="v1/js/ff/transactions/show.js?v={{ FF_VERSION }}"
            nonce="{{ JS_NONCE }}"></script>
{% endblock %}
```

**Comment by JC5** [comment]
Alright, could you remove the entirety of line 444? It starts with `<h4`. 

We'll tackle this live lol.

**Comment by zeitwidrig** [comment]
That does fix it 😄 As in: the transaction page renders but without any tags obviously.

**Comment by JC5** [comment]
Alright, we're getting there. Change line 443 to this. You can restore line 444.

```
{% if null != tag.id and '' != tag.id %}
```

**Comment by zeitwidrig** [comment]
Yay, that's it! 🥳 
Transaction page shows up with tags:

<img width="422" height="70" alt="Image" src="https://github.com/user-attachments/assets/60b6cff5-dfc0-4261-ac51-c3c83e9bedc6" />

**Comment by JC5** [comment]
Very good! There's still a part of Firefly III that is collecting deleted tags. But I have something to go on for sure.

Thanks for your help and your patience, I will add this to Firefly III v6.4.1.

**Comment by Cryptec** [comment]
i have the same issue, glad there is already a fix :)

**Comment by zynexiz** [comment]
> Very good! There's still a part of Firefly III that is collecting deleted tags. But I have something to go on for sure.
> 
> Thanks for your help and your patience, I will add this to Firefly III v6.4.1.

Changed line 443 manually meanwhile, works without issue now 😄

**Comment by frank-bg** [comment]
![image](https://github.com/user-attachments/assets/63695e5d-538e-4d37-8b4e-6bea326089fd)

clear cache fixed it for me, I am still at v6.3.2
