### ISSUE TITLE
Drop down for To / Category fields in mass edit

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#1532]
**Bug description**
I am running Firefly III version 4.7.4

When mass editing entries which I've just imported the To and Category drop downs are not aligning correctly based on the CSS.

**Steps to reproduce**
What do you need to do to trigger this bug?

- Select multiple entries to edit
- Begin typing into the To or Category field
- See the dropdown appear top left of the table area rather than under the field as expected

This looks like a simple CSS issue, the individual TD needs to have position:relative so that the dropdown will go underneath

**Extra info**
Chrome 67.0.3396.99 on Windows 10
- Screenshot without CSS edit:
![image](https://user-images.githubusercontent.com/3290527/42294400-6d60941a-7fd8-11e8-91da-d8a1d3c50133.png)

- Screenshot with CSS adjusted on the TD to set position:relative value
![image](https://user-images.githubusercontent.com/3290527/42294468-fdef96c0-7fd8-11e8-9e7e-3e9408c04f79.png)

**Comment by JC5** [comment]
Thanks, this is much appreciated! I've pushed a fix!

**Comment by lucavallerini** [comment]
@JC5 Just to let you know that this behaviour happens also when creating/editing a rule, in case the fix does not solve the problem there too.

**Comment by JC5** [comment]
I actually knew about that one and not the one in the mass edit routine. I think I fixed them both on the demo site. If you see other problem areas please let me know!
