### ISSUE TITLE
FreeIPA LDAP integration not working

### ISSUE THREAD

**Issue by MrShibe** [firefly-iii/firefly-iii#1933]
I am running Firefly III version 4.7.8

**Description**
Long time listener, first time caller. Was quite excited to see the new LDAP support, but I've been having a bit of trouble getting it up and running.

Firstly I appreciate that this may be down to my configuration/LDAP server, so if that's the case let me know, but I've been unable to get this to work so far and my current theory is that it's due to how the LDAP Search query is constructed.

I have setup a fresh install of Firefly-III and tried to enable authentication using FreeIPA LDAP. The requests are going through to my LDAP server, but no user is able to authenticate. Firefly-III logs are empty, but the LDAP logs reveal:

```
[28/Dec/2018:19:52:33.445822995 +0000] conn=1540 fd=127 slot=127 connection from [IP address of Firefly-III server] to [IP address of FreeIPA server]
[28/Dec/2018:19:52:33.446216398 +0000] conn=1540 op=0 BIND dn="uid=firefly,cn=sysaccounts,cn=etc,dc=example,dc=com" method=128 version=3
[28/Dec/2018:19:52:33.446582144 +0000] conn=1540 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0000687768 dn="uid=firefly,cn=sysaccounts,cn=etc,dc=example,dc=com"
[28/Dec/2018:19:52:33.451612889 +0000] conn=1540 op=1 SRCH base="dc=example,dc=com" scope=2 filter="(&(objectClass=person)(userprincipalname=*)(uid=tshibe))" attrs="* aci"
[28/Dec/2018:19:52:33.452634743 +0000] conn=1540 op=1 RESULT err=0 tag=101 nentries=0 etime=0.0001125688
[28/Dec/2018:19:52:33.464429168 +0000] conn=1540 op=2 UNBIND
```

 From looking at the 4th line, it appears that the LDAP search is using three criteria:

- objectClass=person (this is fine)
- userprincipalname=* (this returns 0 results when I try to search it myself, I do not believe FreeIPA has a UPN field)
- uid=tshibe (this is fine)

It appears to me that the attempt to find a UPN is causing the search to return 0 results, failing the authentication. Is this due to how Firefly-III is making the request, or is it something I've missed on the FreeIPA side? (Or alternatively is it something else entirely?)

In my Firefly-III .env file, I have the following set for my LDAP settings:

```
ADLDAP_CONNECTION_SCHEME=FreeIPA
ADLDAP_AUTO_CONNECT=true

# LDAP connection settings
ADLDAP_CONTROLLERS= [IP address of FreeIPA server]
ADLDAP_PORT=389
ADLDAP_TIMEOUT=5
ADLDAP_BASEDN="dc=example,dc=com"
ADLDAP_FOLLOW_REFFERALS=false
ADLDAP_USE_SSL=false
ADLDAP_USE_TLS=false

ADLDAP_ADMIN_USERNAME=firefly
ADLDAP_ADMIN_PASSWORD=[Firefly LDAP account password]

ADLDAP_ACCOUNT_PREFIX="uid="
ADLDAP_ACCOUNT_SUFFIX=",cn=users,cn=accounts,dc=example,dc=com"
ADLDAP_ADMIN_ACCOUNT_PREFIX="uid="
ADLDAP_ADMIN_ACCOUNT_SUFFIX=",cn=sysaccounts,cn=etc,dc=example,dc=com"

# LDAP authentication settings.
ADLDAP_PASSWORD_SYNC=false
ADLDAP_LOGIN_FALLBACK=false

ADLDAP_DISCOVER_FIELD=uid
ADLDAP_AUTH_FIELD=uid

# Will allow SSO if your server provides an AUTH_USER field.
WINDOWS_SSO_DISCOVER=samaccountname
WINDOWS_SSO_KEY=AUTH_USER

# field to sync as local username.
ADLDAP_SYNC_FIELD=uid
```

**Extra info**
Firefly-III running on Ubuntu 18.04, FreeIPA running on CentOS 7

**Comment by JC5** [comment]
Unless it's a configuration mistake that can't be transferred from Firefly III to [the library I use](https://github.com/adldap/adLDAP), there is not much I can do unfortunately.

**Comment by MrShibe** [comment]
I figured that might be the case. I'll tinker about and post here if I get it working.

Thanks anyhow.

**Comment by JC5** [comment]
> Long time listener, first time caller.

And I just noticed that. Nice :grin:

**Comment by MrShibe** [comment]
Okay, I've got it working, but it's a bit of a bodge job.

By creating my own custom object class and creating a userprincipalname attribute type within that class, I can give the user a userprincipalname, so that when the LDAP query's filter looks up for any value in the userprincipalname field, it can find something and actually authenticate the user.

Why the ADLDAP library is searching for the UPN field when we've specified we're using FreeIPA I don't know, and to tell the truth I'm happy with my lazy solution for now rather than digging into exactly why that's happening.

So, in case anyone else uses FreeIPA and stumbles upon this, I figured I may as well document the whole integration process from start to finish (because FreeIPA's documentation is lacking in some areas, thankfully the Firefly stuff is straight forward):

**Setting up FreeIPA LDAP Integration with Firefly**
Use `"ldapmodify -x -D 'cn=Directory Manager' -W` to edit LDAP, the .env file in my original post can also be used as a template, but the settings are self-explanatory and well explained in the Firefly documentation.

**Create Firefly system user**
```
dn: uid=firefly,cn=sysaccounts,cn=etc,dc=example,dc=com
changetype: add
objectclass: account
objectclass: simplesecurityobject
uid: firefly
userPassword: passwordGoesHere
passwordExpirationTime: 20380119031407Z
nsIdleTimeout: 0
```
The uid and userPassword should match the settings in your Firefly .env file.

Next we need to give the Firefly user permissions over the users directory through aci, so that it can authenticate them:

```
dn: cn=users, cn=accounts, dc=example, dc=com
changetype: modify
add: aci
aci: (targetattr="*")(version 3.0; acl "Firefly user can read/search."; allow (read, search) userdn = "ldap:///uid=firefly,cn=sysaccounts,cn=etc,dc=example,dc=com";)
```

**userprincipalname bodge**
As the ADLDAP module for some reason searches for a userprincipalname (not a particular UPN mind you, just the existence of one) my solution to allow it to find users is to give my users a userprincipalname. The purpose of this field is solely to allow the user to be found by LDAP queries, and has no tangible bearing on the system beyond this.

First we create our userprincipalname attribute type (the OID here was chosen at random):
```
dn: cn=schema
changetype: modify
add: attributeTypes
attributeTypes: ( 2.5.6.6.1 NAME 'userprincipalname' SYNTAX 1.3.6.1.4.1.1466.115.121.1.15)
```
Next we want to create our own object class for it to live in (rather than bolt it onto an built in object class that may get overwritten in an update):
```
dn: cn=schema
changetype: modify
add: objectclasses
objectclasses: ( 2.5.6.6.2 NAME 'bodge' SUP person STRUCTURAL MAY ( userprincipalname ) )
```
Now we need ipa to pick up our new object class, so run `ipa config-mod --addattr=ipaUserObjectClasses=bodge`

Back to LDAP, now we need to add the object class to our user:
```
dn: uid=myuser,cn=users,cn=accounts,dc=example,dc=com
changetype: modify
add: objectClass
objectClass: bodge
```
Finally, we give our user a userprincipalname (I've set this to be the same as the uid, but this could be absolutely anything, so long as it's not null):
```
dn: uid=myuser,cn=users,cn=accounts,dc=example,dc=com
changetype: modify
add: userprincipalname
userprincipalname: myuser
```
Now when Firefly sends an LDAP query to FreeIPA, the filter looks for a user who:

- Has the person objectClass (to ensure they're a user)
- Has a userprincipalname (which they do now thanks to our bodge)
- Has a uid that matches whatever the user logged in with

Upon finding this, the user can then be authenticated, assuming their login credentials are valid.

**Comment by stevebauman** [comment]
Hi @MrShibe, developer of Adldap2 and Adldap2-Laravel here. This problem seems to be the scopes that are being applied in the `adldap_auth.php` configuration file here:

https://github.com/firefly-iii/firefly-iii/blob/f57fc06347fb3e5fcab1c662ac198d9248eb6ee4/config/adldap_auth.php#L7-L20

As you've shown, FreeIPA does not have UserPrincipalName's. The `UpnScope` is being applied when `FreeIPA` is the configured LDAP server. This scope is built in only for ActiveDirectory because valid users in ActiveDirectory *always* contain a UPN.

Can you remove the `UpnScope` from your `config/adldap_auth.php` file and try again?

I'll always be glad to assist with any issues in any of my packages. We'll get you up and running :smile:

Let me know if it works!

**Comment by stevebauman** [comment]
To elaborate, the `scopes` configuration feature allows you to limit the query at which users are discovered when authenticating an LDAP user.

For example, you could add a scope which applies a query to only return users who are members of a certain group or are contained in an OU. This would effectively restrict your application from allowing other valid LDAP users who are authenticating.

**Comment by JC5** [comment]
I've pushed a change to Firefly III that will do this in the next release. @MrShibe, you'll have to do it manually until the next release comes out.

**Comment by MrShibe** [comment]
Thanks very much for both of your help guys, I appreciate it.

When the next release is out I'll remove my manual workaround and test this.

**Comment by wrouesnel** [comment]
Running the current master branch, I'm still seeing this issue with FreeIPA (deployed under docker).

My `.env` file

```
# Firefly III has two options for user authentication. "eloquent" is the default,
# and "ldap" for LDAP servers.
# For full instructions on these settings please visit:
# https://firefly-iii.readthedocs.io/en/latest/installation/authentication.html
LOGIN_PROVIDER=ldap

# LDAP connection configuration
ADLDAP_CONNECTION_SCHEME=FreeIPA
ADLDAP_AUTO_CONNECT=true

# LDAP connection settings
ADLDAP_CONTROLLERS=ipa.##MASKED##.##MASKED##.com
ADLDAP_PORT=389
ADLDAP_TIMEOUT=5
ADLDAP_BASEDN="cn=users,cn=accounts,dc=##MASKED##,dc=##MASKED##,dc=com"
ADLDAP_FOLLOW_REFFERALS=False
ADLDAP_USE_SSL=False
ADLDAP_USE_TLS=False

ADLDAP_ADMIN_USERNAME=uid=svc_accounting,cn=users,cn=accounts,dc=##MASKED##,dc=##MASKED##,dc=com
ADLDAP_ADMIN_PASSWORD="##MASKED##"

ADLDAP_ACCOUNT_PREFIX="uid="
ADLDAP_ACCOUNT_SUFFIX=",cn=users,cn=accounts,dc=##MASKED##,dc=##MASKED##,dc=com"

# LDAP authentication settings.
ADLDAP_PASSWORD_SYNC=false
ADLDAP_LOGIN_FALLBACK=false

ADLDAP_DISCOVER_FIELD=uid
ADLDAP_AUTH_FIELD=uid

# Will allow SSO if your server provides an AUTH_USER field.
WINDOWS_SSO_DISCOVER=
WINDOWS_SSO_KEY=

# field to sync as local username.
ADLDAP_SYNC_FIELD=uid
```

and the top of `config/ldap_auth.php` (from the deployed container)
```
declare(strict_types=1);

use Adldap\Laravel\Scopes\UidScope;
use Adldap\Laravel\Scopes\UpnScope;


// default OpenLDAP scopes.
$scopes = [
    UidScope::class,
];
if ('FreeIPA' === env('ADLDAP_CONNECTION_SCHEME')) {
    $scopes = [];
}
if ('ActiveDirectory' === env('ADLDAP_CONNECTION_SCHEME')) {
    $scopes = [
        UpnScope::class,
    ];
}
```

But when I try to connect I'm still seeing an attempt to find userprinciplename - 
```
[10/Mar/2019:22:06:10.633823374 +0000] conn=1052 op=0 BIND dn="uid=svc_accounting,cn=users,cn=accounts,dc=##MASKED##,dc=##MASKED##,dc=com" method=128 version=3
[10/Mar/2019:22:06:10.635183622 +0000] conn=1052 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0001689006 dn="uid=svc_accounting,cn=users,cn=accounts,dc=##MASKED##,dc=##MASKED##,dc=com"
[10/Mar/2019:22:06:10.638270504 +0000] conn=1052 op=1 SRCH base="cn=users,cn=accounts,dc=##MASKED##,dc=##MASKED##,dc=com" scope=2 filter="(&(objectClass=organizationalPerson)(objectClass=person)(userprincipalname=will))" attrs="* aci"
[10/Mar/2019:22:06:10.641902268 +0000] conn=1052 op=1 RESULT err=0 tag=101 nentries=0 etime=0.0003742637
[10/Mar/2019:22:06:10.645510564 +0000] conn=1052 op=2 UNBIND
[10/Mar/2019:22:06:10.645558401 +0000] conn=1052 op=2 fd=106 closed - U1
```
