### ISSUE TITLE
Duplicate transfer detected during csv import

### ISSUE THREAD

**Issue by VoidAndAny** [firefly-iii/firefly-iii#2166]
**Bug description**
I am running Firefly III version 4.7.14, and I have strange duplicate transfer (not it's a bug)

Example, the following transaction:
```
date-transaction;_ignore;amount;_ignore;note;_ignore;_ignore;account-name;category-name;opposing-name
2015-04-05;;50;CPTE Compte chèque;;R;;CPTE Assurance Simon;Virement;CPTE Compte chèque
```
(column mapping used in the first row)

Is reported as duplicate with the following operation (previously imported)
![Capture d’écran 2019-03-11 à 13 23 51](https://user-images.githubusercontent.com/796787/54123837-0f11ed80-4401-11e9-9e07-4bce1ff43262.png)

Previously imported, extract of the csv file: 
```
date-transaction;_ignore;amount;_ignore;note;_ignore;_ignore;account-name;category-name;opposing-name
2015-04-05;;50;CPTE Compte chèque;;;;CPTE Assurance Benjamin;Virement;CPTE Compte chèque
```

Excerpt of Debug log of the import process for the line:
```
[2019-03-11 12:56:55] local.DEBUG: Now at item 1 out of 47
[2019-03-11 12:56:55] local.DEBUG: The hash is: 9a8f9985f4a004d1fddb08054ae2a7e50e6464465b87de61d008618573da6eaf
[2019-03-11 12:56:55] local.DEBUG: JSON encoded hash is: "9a8f9985f4a004d1fddb08054ae2a7e50e6464465b87de61d008618573da6eaf"
[2019-03-11 12:56:55] local.DEBUG: Hash of hash is: c57a7eb9df145f1fb7a20fbb15d03b14f59f853438a0df64a1209f4578f721ad
[2019-03-11 12:56:55] local.DEBUG: Result is null
[2019-03-11 12:56:55] local.DEBUG: Found no transactions with hash 9a8f9985f4a004d1fddb08054ae2a7e50e6464465b87de61d008618573da6eaf.
[2019-03-11 12:56:55] local.DEBUG: Check if is a double transfer.
[2019-03-11 12:56:55] local.DEBUG: Required hits for transfer comparison is 4
[2019-03-11 12:56:55] local.DEBUG: Array has 1 transactions.
[2019-03-11 12:56:55] local.DEBUG: System has 268 existing transfers
...
...
...
[2019-03-11 12:56:55] local.DEBUG: Now looking at transaction journal #172
[2019-03-11 12:56:55] local.DEBUG: Amount 50 compared to 50.000000000000
[2019-03-11 12:56:55] local.DEBUG: Comparison is a hit! (1)
[2019-03-11 12:56:55] local.DEBUG: Comparing "" to "(empty description)" (original: "")
[2019-03-11 12:56:55] local.DEBUG: Comparison is a hit! (2)
[2019-03-11 12:56:55] local.DEBUG: Comparing dates "2015-04-05 00:00:00" to "2015-04-05 00:00:00"
[2019-03-11 12:56:55] local.DEBUG: Comparison is a hit! (3)
[2019-03-11 12:56:55] local.DEBUG: Comparing current transaction source+dest IDs [31,41]
[2019-03-11 12:56:55] local.DEBUG: .. with current transfer source+dest IDs [31,38]
[2019-03-11 12:56:55] local.DEBUG: Comparing current transaction source+dest names ["",""]
[2019-03-11 12:56:55] local.DEBUG: .. with current transfer source+dest names ["CPTE Assurance Benjamin",0]
[2019-03-11 12:56:55] local.INFO: Transaction is a duplicate transfer, and will not be imported (such a transfer exists already). {"description":"","amount":"50","date":"2015-04-05 00:00:00"}
[2019-03-11 12:56:55] local.WARNING: Row #0 seems to be a duplicate entry and will be ignored.
```

Date, amount and description are the same it's alright but the source+dest name are not.
There is 3 hits and this transfer require 4 hits.

I checked the code (I'me an old, rusted php developper) but they're is 2 things questionning me.

https://github.com/firefly-iii/firefly-iii/blob/87c8b3d7c6e7334ba9cb06957aa1a5f6279cdb76/app/Import/Storage/ImportArrayStorage.php#L589 : Why ++$hits is after log.debug ? Not a deal in my case but can be confusing

https://github.com/firefly-iii/firefly-iii/blob/87c8b3d7c6e7334ba9cb06957aa1a5f6279cdb76/app/Import/Storage/ImportArrayStorage.php#L592 : Why do you add +1 to hits to have the totalHits ? In my case I have "only" 3 hits this line add one so I'm equal to the max acceptable hits (4)

Thanks for your time.

Yoann

**Comment by JC5** [comment]
> Why ++$hits is after log.debug

Have you not seen the if-statement?

> Why do you add +1 to hits to have the totalHits ? 

Because split transactions are a thing.  


Regarding your question. A database change (changing from date to datetime) can cause duplicate imports. Not much I can do unfortunately. Just delete them and move on, it won’t happen in the future.

**Comment by VoidAndAny** [comment]
Sorry, I think I wasn't clear.
For the ++hits my concern is that it occurs before the log.debug but for all other test it is after.
So in this case the value logged is not correct (because hits is not incremented yet).

For the second point and my problem is not that some transfer are duplicated but they are not imported.
Import detect them as duplicated but they are not, date, amount and description are the same but not the source+dest name.

I think, it because of the +1 on totalHits so transfer is rejected with only 3 common items.

**Comment by JC5** [comment]
I’ll check it out when I have a pc.

**Comment by JC5** [comment]
I have added some debug info but I am not sure what you mean with this:

>  : Why do you add +1 to hits to have the totalHits ? In my case I have "only" 3 hits this line add one so I'm equal to the max acceptable hits (4)

**Comment by JC5** [comment]
Alright I found at least one bug so far. :grin:

**Comment by JC5** [comment]
Alright so I've run some tests and everything seems to be in order now. I'll push a new release soon that should fix this right up.

**Comment by VoidAndAny** [comment]
Sorry to re-open this issue but there still have a bug.
My transaction/transfer are still detected as duplicated but they are not..

The end of the function is strange (I don't understand it), I think the problem can came from that $totalHits is never reset so in my example it pass from 3 to 6: 

```
[2019-03-19 13:36:50] local.DEBUG: Now looking at transaction journal #222
[2019-03-19 13:36:50] local.DEBUG: Amount 50 compared to 50.000000000000
[2019-03-19 13:36:50] local.DEBUG: Comparison is a hit! (1)
[2019-03-19 13:36:50] local.DEBUG: Comparing "" to "(empty description)" (original: "")
[2019-03-19 13:36:50] local.DEBUG: Comparison is a hit! (2)
[2019-03-19 13:36:50] local.DEBUG: Comparing dates "2015-04-05 00:00:00" to "2015-04-05 00:00:00"
[2019-03-19 13:36:50] local.DEBUG: Comparison is a hit! (3)
[2019-03-19 13:36:50] local.DEBUG: Comparing current transaction source+dest IDs [31,41]
[2019-03-19 13:36:50] local.DEBUG: .. with current transfer source+dest IDs [31,39]
[2019-03-19 13:36:50] local.DEBUG: Source IDs are not the same.
[2019-03-19 13:36:50] local.DEBUG: Comparing current transaction source+dest names ["",""]
[2019-03-19 13:36:50] local.DEBUG: .. with current transfer source+dest names ["CPTE Assurance Maël","CPTE Compte chèque"]
[2019-03-19 13:36:50] local.DEBUG: Source names are not the same.
[2019-03-19 13:36:50] local.DEBUG: Total hits is now 3, hits is 3



[2019-03-19 13:36:50] local.DEBUG: Now looking at transaction journal #172
[2019-03-19 13:36:50] local.DEBUG: Amount 50 compared to 50.000000000000
[2019-03-19 13:36:50] local.DEBUG: Comparison is a hit! (1)
[2019-03-19 13:36:50] local.DEBUG: Comparing "" to "(empty description)" (original: "")
[2019-03-19 13:36:50] local.DEBUG: Comparison is a hit! (2)
[2019-03-19 13:36:50] local.DEBUG: Comparing dates "2015-04-05 00:00:00" to "2015-04-05 00:00:00"
[2019-03-19 13:36:50] local.DEBUG: Comparison is a hit! (3)
[2019-03-19 13:36:50] local.DEBUG: Comparing current transaction source+dest IDs [31,41]
[2019-03-19 13:36:50] local.DEBUG: .. with current transfer source+dest IDs [31,38]
[2019-03-19 13:36:50] local.DEBUG: Source IDs are not the same.
[2019-03-19 13:36:50] local.DEBUG: Comparing current transaction source+dest names ["",""]
[2019-03-19 13:36:50] local.DEBUG: .. with current transfer source+dest names ["CPTE Assurance Benjamin","CPTE Compte chèque"]
[2019-03-19 13:36:50] local.DEBUG: Source names are not the same.
[2019-03-19 13:36:50] local.DEBUG: Total hits is now 6, hits is 3
```

**Comment by JC5** [comment]
Could you share some lines of the CSV over email?

**Comment by JC5** [comment]
Thanks. I think I found the issue and I'll push a fix for the next release :+1:

I appreciate the pointers you gave me!

**Comment by VoidAndAny** [comment]
Hello, 
Do you known when next release will occur ?

Thanks

**Comment by JC5** [comment]
No.
