### ISSUE TITLE
demo website: no username/password

### ISSUE THREAD

**Issue by blackout314** [firefly-iii/firefly-iii#2259]
I am running Firefly III version DEMO

**Description**
no username password for try :)

**Comment by JC5** [comment]
Thanks, I see the info is missing. Username is `demo@firefly`, password is `demo`.

I'll fix it in a few hours.

**Comment by JC5** [comment]
Fixed! :+1:

**Comment by riffraff** [comment]
it seems to me this is still an issue, the user/password is not mentioned in the website, the readme or the demo site

**Comment by JC5** [comment]
It's right there. Might have been visiting exactly during a reset.
