### ISSUE TITLE
[Question] Some source accounts are not found during the import?

### ISSUE THREAD

**Issue by leander091** [firefly-iii/firefly-iii#3258]
I am running Firefly III version 5.2.1.

**Description**
I have an other question about the CSV importer. :)

I saw some errors related to the last import run, so I checked the database and the source accounts are available on the database. 
It looks like these errors are related to some transfers from one person to me.  

Could you give me some guidelines to find the culprit? 
```
Error(s)

    Line #24:
        (2) transactions.0.source_id: Could not find a valid source account when searching for ID "238" or name "". (original value: "238")
        (2) transactions.0.source_name: Could not find a valid source account when searching for ID "238" or name "". (original value: "(not found)")
    Line #254:
        (2) transactions.0.source_id: Could not find a valid source account when searching for ID "238" or name "". (original value: "238")
        (2) transactions.0.source_name: Could not find a valid source account when searching for ID "238" or name "". (original value: "(not found)")
    Line #503:
        (2) transactions.0.source_id: Could not find a valid source account when searching for ID "238" or name "". (original value: "238")
        (2) transactions.0.source_name: Could not find a valid source account when searching for ID "238" or name "". (original value: "(not found)")
    Line #711:
        (2) transactions.0.source_id: Could not find a valid source account when searching for ID "238" or name "". (original value: "238")
        (2) transactions.0.source_name: Could not find a valid source account when searching for ID "238" or name "". (original value: "(not found)")
    Line #724:
        (2) transactions.0.source_id: Could not find a valid source account when searching for ID "238" or name "". (original value: "238")
        (2) transactions.0.source_name: Could not find a valid source account when searching for ID "238" or name "". (original value: "(not found)")
    Line #751:
        (2) transactions.0.source_id: Could not find a valid source account when searching for ID "281" or name "". (original value: "281")
        (2) transactions.0.source_name: Could not find a valid source account when searching for ID "281" or name "". (original value: "(not found)")
```

**Extra info**
 

**Bonus points**

- [ ] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [ ] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
Check your logs. The same error should be there as well, together with the original transaction the CSV importer is trying to submit.

Could you collect some details for me?

- The "type" the CSV importer is trying to create.
- The account type of the source_id and destination_id. You'll have to look them up in your Firefly III installation.

I suspect that Firefly III is trying to create a withdrawal (for example) but uses a revenue account instead of a expense account. I'll need to do some experimentation to see what the best way is to avoid that.

**Comment by leander091** [comment]
Sure thing,

Based on the logs available the importer is indeed trying to create a withdrawal instead of an Deposit from an revenue account. 

The account with source account_id 238 is an Expense account and the destination id is my asset account.

**Comment by Moc** [comment]
Just watching along here as I had a similar result when doing the import this morning (with the latest files, to include the fix for previously reported error).

**Comment by JC5** [comment]
Ok, I've just released 1.0.2 that should have a fix for this issue. If an account exist with the specified name but it is of the wrong type, you should see something like this:

```
local.WARNING: The found destination account is of type revenue but this is a withdrawal. Out of cheese error.
```
Check out the submission just a few lines below to see if it's correct. In my case "coffee" is submitted as the "destination_name". This could also be the "source_name".

I removed all fields that aren't important for this issue:

```
local.DEBUG: Submitting to Firefly III: {[{
"type":"withdrawal",
"source_id":1,"source_name":null
,"destination_id":null,"destination_name":"coffee"}]}
```

**Comment by leander091** [comment]
Thanks for the for the fix and the new version. I have tested it with an new import file with only the affected transactions. But i see that my import issue still exist.

Could it be related that my revenue account and my expense account have the same name so the importer is confused about that?

**Comment by JC5** [comment]
That was specifically what I was trying to fix. Could you send me some transactions over email, so i can try this myself?

**Comment by leander091** [comment]
Ofcouse i'am going to send the mail in a moment.

**Comment by JC5** [comment]
Alright, thanks. Before you do, are you specifically mapping accounts (like these expense/revenue accounts) or are you sending them to Firefly III "as is"?

**Comment by leander091** [comment]
In this case i have not mapped any account, so that the auto mapper could do the work.

**Comment by JC5** [comment]
I got it, thanks.

Unfortunately I was unable to trigger any problems. I did find some other issues so I'll release 1.0.3 tonight. I hope that will fix the problem on your end as well.

I expect that it will start duplicating at first (a warning will be in the changelog) so becareful importing large overlaps.

**Comment by leander091** [comment]
Did you test my file with two existing accounts? I could trigger this problem by creating a expense and a revenue account both with the name: Sample account Name and IBAN number NL53INGB0007654112

**Comment by JC5** [comment]
I did yes, but I'll verify. It works now for me, so it could be fixed for sure. Here's what my importer tries to submit to Firefly III:

```
{
	"group_title": null,
	"error_if_duplicate_hash": true,
	"transactions": [{
		"type": "deposit",
		"date": "2020-03-20",
		"currency_id": 1,
		"currency_code": null,
		"amount": "25.000000000000",
		"amount_modifier": "1",
		"description": "Datum/Tijd: 20-03-2020 17:59:17",
		"source_id": null,
		"source_name": "Sample account Name",
		"destination_id": 1,
		"destination_name": null,
		"source_iban": "NL53INGB0007654112",
		"destination_iban": null,
		"original_source": "jc5-csv-import-v1.0.3",
		"tags": [],
		"source_number": null,
		"source_bic": null,
		"destination_number": null,
		"destination_bic": null
	}]
}
```

**Comment by leander091** [comment]
Allright, im going to wait until the new version arrives and test it again :)

Thanks you for the hard work on this project.

**Comment by JC5** [comment]
New version is out. Keep an eye on [the changelog](https://github.com/firefly-iii/csv-importer/releases/tag/1.0.3)

**Comment by leander091** [comment]
I have updated to the new version of both FF3 and the csv-importer and ran some tests.  My first test subject was to import my example file to create sample deposits and the file imported without any problems.  

For the second test I extracted the faulty deposit transactions from my earlier import. These transactions were also imported without any problems and were correctly created in FF3.
