### ISSUE TITLE
Unable to acces GUI after install (docker)

### ISSUE THREAD

**Issue by pape92** [firefly-iii/firefly-iii#3285]
i keep gettings whoops screen

Logs: 
`docker logs -f 7d0808368f87
Now in entrypoint.sh for Firefly III
Entrypoint script version is 1.0.4 (2020-03-05)
Now parsing _FILE variables.
done!
Making directories...
SQL connection data: (pw is hidden)
DB_CONNECTION: ''
DB_HOST: '10.0.1.1'
DB_PORT: '5432'
DB_DATABASE: 'firefly'
DB_USERNAME: 'firefly'
Touch DB file (if SQLite)...
Run chown on /mnt/cache/appdata/firefly-iii//storage...
Run chmod on /mnt/cache/appdata/firefly-iii//storage...
Remove log file...
Dump auto load...
Generating optimized autoload files
Deprecation Notice: Class Fhp\DataElementGroups\KeyNameTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/KeyNameTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityDateTimeTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityDateTimeTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityIdentificationDetailsTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityIdentificationDetailsTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityProfileTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityProfileTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SignatureAlgorithmTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SignatureAlgorithmTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\BinTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/BinTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\DatTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/DatTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KikTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KikTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtiTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtiTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtvTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtvTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\Message\MessageTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/Message/MessageTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\ResponseTest\ResponseTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/ResponseTest/ResponseTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 5429 classes
Discover packages...
Discovered Package: adldap2/adldap2-laravel
Discovered Package: davejamesmiller/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: jc5/google2fa-laravel
Discovered Package: laravel/passport
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
Wait for the database.
wait-for-it.sh: waiting 60 seconds for 10.0.1.1:5432
wait-for-it.sh: 10.0.1.1:5432 is available after 0 seconds
DB is up. Time to execute artisan commands.
Run various artisan commands...
Application cache cleared!
Running migration commands...
CreateDB does not apply to "", skipped.
Nothing to migrate.
Seeding: AccountTypeSeeder
[2020-04-22 00:22:35] local.INFO: Could not create account type "Default account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Cash account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Asset account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Expense account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Revenue account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Initial balance account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Beneficiary account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Import account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Loan". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Reconciliation account". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Debt". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create account type "Mortgage". It might exist already.  
Seeded:  AccountTypeSeeder (0.01 seconds)
Seeding: TransactionCurrencySeeder
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "EUR". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "HUF". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "GBP". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "UAH". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "PLN". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "TRY". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "USD". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "BRL". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "CAD". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "IDR". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "AUD". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "NZD". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "EGP". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "MAD". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "ZAR". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "JPY". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "RMB". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "RUB". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "INR". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "XBT". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "BCH". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "ETH". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "ILS". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "CHF". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction currency "HRK". It might exist already.  
Seeded:  TransactionCurrencySeeder (0.02 seconds)
Seeding: TransactionTypeSeeder
[2020-04-22 00:22:35] local.INFO: Could not create transaction type "Withdrawal". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction type "Deposit". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction type "Transfer". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction type "Opening balance". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create transaction type "Reconciliation". It might exist already.  
Seeded:  TransactionTypeSeeder (0 seconds)
Seeding: PermissionSeeder
[2020-04-22 00:22:35] local.INFO: Could not create role "Site Owner". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create role "Demo User". It might exist already.  
Seeded:  PermissionSeeder (0 seconds)
Seeding: LinkTypeSeeder
[2020-04-22 00:22:35] local.INFO: Could not create link type "Related". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create link type "Refund". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create link type "Paid". It might exist already.  
[2020-04-22 00:22:35] local.INFO: Could not create link type "Reimbursement". It might exist already.  
Seeded:  LinkTypeSeeder (0 seconds)
Seeding: ConfigSeeder
[2020-04-22 00:22:35] local.WARNING: Database entry exists. Update to latest version (13)  
Seeded:  ConfigSeeder (0 seconds)
Database seeding completed successfully.
Going to decrypt the database.
No decryption required for table "accounts".
No decryption required for table "attachments".
No decryption required for table "bills".
No decryption required for table "budgets".
No decryption required for table "categories".
No decryption required for table "piggy_banks".
No decryption required for table "preferences".
No decryption required for table "tags".
No decryption required for table "transaction_journals".
No decryption required for table "transactions".
No decryption required for table "journal_links".
Done!
Running upgrade commands...
This command has already been executed.
Database already seems to be migrated.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
No incorrectly stored credit card liabilities.
This command has already been executed.
This command has already been executed.
This command has already been executed.
Running verification commands...
All piggy bank events are correct.
Verified the content of 0 piggy bank events in 0.01 seconds.
All link types OK!
Verified link types in 0.01 seconds
All access tokens OK!
Verify access tokens in 0.01 seconds.
All transaction journals have correct bill information.
Verified bills / journals in 0.01 seconds
0 different currencies are currently in use.
All currencies are correctly enabled or disabled.
Verified currencies in 0.01 seconds.
No invalid budget/journal entries.
Verified budget/journals in 0.01 seconds.
Amount integrity OK!
Verified amount integrity in 0.01 seconds
No zero-amount transaction journals.
Verified zero-amount integrity in 0.01 seconds
No orphaned transactions.
No orphaned accounts.
Verified orphans in 0.01 seconds
No uneven transaction journals.
No empty transaction journals.
Verified empty journals in 0 seconds
Verified empty groups in 0.01 seconds
All account types are OK!
Verifying account types took 0.01 seconds
All meta fields are correct.
Renamed meta fields in 0.01 seconds
Going to verify 0 opening balance transactions.
There was nothing to fix in the opening balance transactions.
Verified all transaction group and journal title lengths in 0.01 seconds.
Corrected recurring transactions 0.01 seconds.
Running report commands...
Report on empty objects finished in 0.01 seconds
Report on total sum finished in 0.01 seconds
Restored OAuth keys from database.
Generating new OAuth keys...
Encryption keys already exist. Use the --force option to overwrite them.
[2020-04-22 00:22:39] local.INFO: OAuth client generated but no user associated.  
Personal access client created successfully.
Client ID: 5
Client secret: ItIs0KDHr1BPWDOOmaF17ZSLUVIGgc5to4CANF73
[2020-04-22 00:22:39] local.INFO: OAuth client generated but no user associated.  
Password grant client created successfully.
Client ID: 6
Client secret: PWQhw0Ycl2ZpctVqDuPpKKTgEIx5vsh5GmVmWF4W
Updated version.
Application cache cleared!
Configuration cache cleared!
Configuration cached successfully!
Run chown on /mnt/cache/appdata/firefly-iii//storage
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.2.2!                                |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.14. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.14. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 22 00:22:40.119189 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.16 OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Apr 22 00:22:40.119215 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
10.0.1.99 - - [22/Apr/2020:00:22:52 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:22:57 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:22:57 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:22:57 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:22:57 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:22:58 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:22:58 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:24:43 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:24:43 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:25:45 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:25:45 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:27:36 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:27:45 +0200] "\x16\x03\x01\x02" 400 0 "-" "-"
10.0.1.99 - - [22/Apr/2020:00:27:45 +0200] "\x16\x03\x01\x02" 400 0 "-" "-"
10.0.1.99 - - [22/Apr/2020:00:27:45 +0200] "\x16\x03\x01\x02" 400 0 "-" "-"
10.0.1.99 - - [22/Apr/2020:00:27:53 +0200] "\x16\x03\x01\x02" 400 0 "-" "-"
10.0.1.99 - - [22/Apr/2020:00:27:53 +0200] "\x16\x03\x01\x02" 400 0 "-" "-"
10.0.1.99 - - [22/Apr/2020:00:27:53 +0200] "\x16\x03\x01\x02" 400 0 "-" "-"
10.0.1.99 - - [22/Apr/2020:00:28:05 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:29:40 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:29:40 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:29:41 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:29:41 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:29:41 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:29:41 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
[Wed Apr 22 00:34:59.001838 2020] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down
Now in entrypoint.sh for Firefly III
Entrypoint script version is 1.0.4 (2020-03-05)
Now parsing _FILE variables.
done!
Making directories...
SQL connection data: (pw is hidden)
DB_CONNECTION: ''
DB_HOST: '10.0.1.1'
DB_PORT: '5432'
DB_DATABASE: 'firefly'
DB_USERNAME: 'firefly'
Touch DB file (if SQLite)...
Run chown on /mnt/cache/appdata/firefly-iii//storage...
Run chmod on /mnt/cache/appdata/firefly-iii//storage...
Remove log file...
Dump auto load...
Generating optimized autoload files
Deprecation Notice: Class Fhp\DataElementGroups\KeyNameTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/KeyNameTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityDateTimeTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityDateTimeTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityIdentificationDetailsTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityIdentificationDetailsTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityProfileTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityProfileTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SignatureAlgorithmTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SignatureAlgorithmTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\BinTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/BinTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\DatTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/DatTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KikTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KikTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtiTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtiTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtvTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtvTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\Message\MessageTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/Message/MessageTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\ResponseTest\ResponseTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/ResponseTest/ResponseTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 5429 classes
Discover packages...
Discovered Package: adldap2/adldap2-laravel
Discovered Package: davejamesmiller/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: jc5/google2fa-laravel
Discovered Package: laravel/passport
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
Wait for the database.
wait-for-it.sh: waiting 60 seconds for 10.0.1.1:5432
wait-for-it.sh: 10.0.1.1:5432 is available after 0 seconds
DB is up. Time to execute artisan commands.
Run various artisan commands...
Application cache cleared!
Running migration commands...
CreateDB does not apply to "", skipped.
Nothing to migrate.
Seeding: AccountTypeSeeder
[2020-04-22 00:36:05] local.INFO: Could not create account type "Default account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Cash account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Asset account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Expense account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Revenue account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Initial balance account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Beneficiary account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Import account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Loan". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Reconciliation account". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Debt". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create account type "Mortgage". It might exist already.  
Seeded:  AccountTypeSeeder (0.01 seconds)
Seeding: TransactionCurrencySeeder
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "EUR". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "HUF". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "GBP". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "UAH". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "PLN". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "TRY". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "USD". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "BRL". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "CAD". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "IDR". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "AUD". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "NZD". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "EGP". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "MAD". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "ZAR". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "JPY". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "RMB". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "RUB". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "INR". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "XBT". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "BCH". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "ETH". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "ILS". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "CHF". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction currency "HRK". It might exist already.  
Seeded:  TransactionCurrencySeeder (0.02 seconds)
Seeding: TransactionTypeSeeder
[2020-04-22 00:36:05] local.INFO: Could not create transaction type "Withdrawal". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction type "Deposit". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction type "Transfer". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction type "Opening balance". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create transaction type "Reconciliation". It might exist already.  
Seeded:  TransactionTypeSeeder (0 seconds)
Seeding: PermissionSeeder
[2020-04-22 00:36:05] local.INFO: Could not create role "Site Owner". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create role "Demo User". It might exist already.  
Seeded:  PermissionSeeder (0 seconds)
Seeding: LinkTypeSeeder
[2020-04-22 00:36:05] local.INFO: Could not create link type "Related". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create link type "Refund". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create link type "Paid". It might exist already.  
[2020-04-22 00:36:05] local.INFO: Could not create link type "Reimbursement". It might exist already.  
Seeded:  LinkTypeSeeder (0 seconds)
Seeding: ConfigSeeder
[2020-04-22 00:36:05] local.WARNING: Database entry exists. Update to latest version (13)  
Seeded:  ConfigSeeder (0 seconds)
Database seeding completed successfully.
Going to decrypt the database.
No decryption required for table "accounts".
No decryption required for table "attachments".
No decryption required for table "bills".
No decryption required for table "budgets".
No decryption required for table "categories".
No decryption required for table "piggy_banks".
No decryption required for table "preferences".
No decryption required for table "tags".
No decryption required for table "transaction_journals".
No decryption required for table "transactions".
No decryption required for table "journal_links".
Done!
Running upgrade commands...
This command has already been executed.
Database already seems to be migrated.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
No incorrectly stored credit card liabilities.
This command has already been executed.
This command has already been executed.
This command has already been executed.
Running verification commands...
All piggy bank events are correct.
Verified the content of 0 piggy bank events in 0.01 seconds.
All link types OK!
Verified link types in 0.01 seconds
All access tokens OK!
Verify access tokens in 0.01 seconds.
All transaction journals have correct bill information.
Verified bills / journals in 0.01 seconds
0 different currencies are currently in use.
All currencies are correctly enabled or disabled.
Verified currencies in 0.01 seconds.
No invalid budget/journal entries.
Verified budget/journals in 0.01 seconds.
Amount integrity OK!
Verified amount integrity in 0.01 seconds
No zero-amount transaction journals.
Verified zero-amount integrity in 0.01 seconds
No orphaned transactions.
No orphaned accounts.
Verified orphans in 0.01 seconds
No uneven transaction journals.
No empty transaction journals.
Verified empty journals in 0 seconds
Verified empty groups in 0.01 seconds
All account types are OK!
Verifying account types took 0.01 seconds
All meta fields are correct.
Renamed meta fields in 0.01 seconds
Going to verify 0 opening balance transactions.
There was nothing to fix in the opening balance transactions.
Verified all transaction group and journal title lengths in 0.01 seconds.
Corrected recurring transactions 0.01 seconds.
Running report commands...
Report on empty objects finished in 0.02 seconds
Report on total sum finished in 0.01 seconds
OAuth keys are OK
Generating new OAuth keys...
Encryption keys already exist. Use the --force option to overwrite them.
[2020-04-22 00:36:09] local.INFO: OAuth client generated but no user associated.  
Personal access client created successfully.
Client ID: 13
Client secret: qbSheK3H70wDsXKFkWCE00J4GzO1lu4GzkqnXdLL
[2020-04-22 00:36:09] local.INFO: OAuth client generated but no user associated.  
Password grant client created successfully.
Client ID: 14
Client secret: gP6NdblWNb3YcqRzroWGwLq146UJGnSbmLFoVMlE
Updated version.
Application cache cleared!
Configuration cache cleared!
Configuration cached successfully!
Run chown on /mnt/cache/appdata/firefly-iii//storage
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.2.2!                                |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.14. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.14. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 22 00:36:10.238427 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.16 OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Apr 22 00:36:10.238451 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
10.0.1.99 - - [22/Apr/2020:00:36:21 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:36:21 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:36:22 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:36:22 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:36:22 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:36:23 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:36:23 +0200] "GET / HTTP/1.1" 500 1785 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
10.0.1.99 - - [22/Apr/2020:00:36:23 +0200] "GET /favicon.ico HTTP/1.1" 200 12317 "http://10.0.1.1:5080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 Edg/81.0.416.58"
![Screenshot_1](https://user-images.githubusercontent.com/15344932/79921289-37f11880-8432-11ea-8c23-6a3415c5bf77.png)
`

**Comment by JC5** [comment]
I'm sorry, but your Docker logs don't actually contain an error.

Please enable debug mode first.

https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode

**Comment by pape92** [comment]
i add the debug parameters dont know for sure if it worked

`docker logs -f 501e92c013ba
Now in entrypoint.sh for Firefly III
Entrypoint script version is 1.0.4 (2020-03-05)
Now parsing _FILE variables.
done!
Making directories...
SQL connection data: (pw is hidden)
DB_CONNECTION: ''
DB_HOST: '10.0.1.1'
DB_PORT: '5432'
DB_DATABASE: 'firefly'
DB_USERNAME: 'firefly'
Touch DB file (if SQLite)...
Run chown on /mnt/cache/appdata/firefly-iii//storage...
Run chmod on /mnt/cache/appdata/firefly-iii//storage...
Remove log file...
Dump auto load...
Generating optimized autoload files
Deprecation Notice: Class Fhp\DataElementGroups\KeyNameTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/KeyNameTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityDateTimeTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityDateTimeTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityIdentificationDetailsTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityIdentificationDetailsTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SecurityProfileTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SecurityProfileTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataElementGroups\SignatureAlgorithmTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataElementGroups/SignatureAlgorithmTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\BinTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/BinTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\DatTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/DatTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KikTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KikTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtiTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtiTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\DataTypes\KtvTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/DataTypes/KtvTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\Message\MessageTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/Message/MessageTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Fhp\ResponseTest\ResponseTest located in ./vendor/mschindler83/fints-hbci-php/lib/Tests/Fhp/ResponseTest/ResponseTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 5429 classes
Discover packages...
Discovered Package: adldap2/adldap2-laravel
Discovered Package: davejamesmiller/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: jc5/google2fa-laravel
Discovered Package: laravel/passport
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
Wait for the database.
wait-for-it.sh: waiting 60 seconds for 10.0.1.1:5432
wait-for-it.sh: 10.0.1.1:5432 is available after 0 seconds
DB is up. Time to execute artisan commands.
Run various artisan commands...
Application cache cleared!
Running migration commands...
CreateDB does not apply to "", skipped.
Nothing to migrate.
Seeding: AccountTypeSeeder
[2020-04-22 09:35:15] local.INFO: Could not create account type "Default account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Cash account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Asset account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Expense account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Revenue account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Initial balance account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Beneficiary account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Import account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Loan". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Reconciliation account". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Debt". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create account type "Mortgage". It might exist already.  
Seeded:  AccountTypeSeeder (0.01 seconds)
Seeding: TransactionCurrencySeeder
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "EUR". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "HUF". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "GBP". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "UAH". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "PLN". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "TRY". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "USD". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "BRL". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "CAD". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "IDR". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "AUD". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "NZD". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "EGP". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "MAD". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "ZAR". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "JPY". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "RMB". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "RUB". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "INR". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "XBT". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "BCH". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "ETH". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "ILS". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "CHF". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction currency "HRK". It might exist already.  
Seeded:  TransactionCurrencySeeder (0.02 seconds)
Seeding: TransactionTypeSeeder
[2020-04-22 09:35:15] local.INFO: Could not create transaction type "Withdrawal". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction type "Deposit". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction type "Transfer". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction type "Opening balance". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create transaction type "Reconciliation". It might exist already.  
Seeded:  TransactionTypeSeeder (0 seconds)
Seeding: PermissionSeeder
[2020-04-22 09:35:15] local.INFO: Could not create role "Site Owner". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create role "Demo User". It might exist already.  
Seeded:  PermissionSeeder (0 seconds)
Seeding: LinkTypeSeeder
[2020-04-22 09:35:15] local.INFO: Could not create link type "Related". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create link type "Refund". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create link type "Paid". It might exist already.  
[2020-04-22 09:35:15] local.INFO: Could not create link type "Reimbursement". It might exist already.  
Seeded:  LinkTypeSeeder (0 seconds)
Seeding: ConfigSeeder
[2020-04-22 09:35:15] local.WARNING: Database entry exists. Update to latest version (13)  
Seeded:  ConfigSeeder (0 seconds)
Database seeding completed successfully.
Going to decrypt the database.
No decryption required for table "accounts".
No decryption required for table "attachments".
No decryption required for table "bills".
No decryption required for table "budgets".
No decryption required for table "categories".
No decryption required for table "piggy_banks".
No decryption required for table "preferences".
No decryption required for table "tags".
No decryption required for table "transaction_journals".
No decryption required for table "transactions".
No decryption required for table "journal_links".
Done!
Running upgrade commands...
This command has already been executed.
Database already seems to be migrated.
[2020-04-22 09:35:16] local.DEBUG: Now in handle()  
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
No incorrectly stored credit card liabilities.
This command has already been executed.
This command has already been executed.
This command has already been executed.
Running verification commands...
All piggy bank events are correct.
Verified the content of 0 piggy bank events in 0.01 seconds.
All link types OK!
Verified link types in 0.01 seconds
All access tokens OK!
Verify access tokens in 0.01 seconds.
All transaction journals have correct bill information.
Verified bills / journals in 0.01 seconds
0 different currencies are currently in use.
All currencies are correctly enabled or disabled.
Verified currencies in 0.01 seconds.
No invalid budget/journal entries.
Verified budget/journals in 0.01 seconds.
Amount integrity OK!
Verified amount integrity in 0.01 seconds
No zero-amount transaction journals.
Verified zero-amount integrity in 0.01 seconds
No orphaned transactions.
No orphaned accounts.
Verified orphans in 0.01 seconds
No uneven transaction journals.
No empty transaction journals.
Verified empty journals in 0 seconds
[2020-04-22 09:35:18] local.DEBUG: Now in FireflyIII\Console\Commands\Correction\DeleteEmptyGroups::handle  
[2020-04-22 09:35:18] local.DEBUG: Count is 0  
Verified empty groups in 0.01 seconds
[2020-04-22 09:35:18] local.DEBUG: Now in fix-account-types  
[2020-04-22 09:35:18] local.DEBUG: Found 0 journals to fix.  
[2020-04-22 09:35:18] local.DEBUG: No journals had to be fixed.  
All account types are OK!
Verifying account types took 0.01 seconds
All meta fields are correct.
Renamed meta fields in 0.01 seconds
Going to verify 0 opening balance transactions.
There was nothing to fix in the opening balance transactions.
Verified all transaction group and journal title lengths in 0.01 seconds.
Corrected recurring transactions 0.01 seconds.
Running report commands...
Report on empty objects finished in 0.01 seconds
Report on total sum finished in 0.01 seconds
Restored OAuth keys from database.
Generating new OAuth keys...
Encryption keys already exist. Use the --force option to overwrite them.
[2020-04-22 09:35:19] local.INFO: OAuth client generated but no user associated.  
Personal access client created successfully.
Client ID: 15
Client secret: p7n6AVIceKIZf099afwgCwhSxQZEfb6Qobyx7CTw
[2020-04-22 09:35:19] local.INFO: OAuth client generated but no user associated.  
Password grant client created successfully.
Client ID: 16
Client secret: UBmBcUtnaKH5IH9vsWi5L23sYQrulBRvTODofzW5
[2020-04-22 09:35:19] local.DEBUG: Set new value for  {"name":"db_version"} 
[2020-04-22 09:35:19] local.DEBUG: Exists already, overwrite value. {"name":"db_version"} 
[2020-04-22 09:35:19] local.DEBUG: Set new value for  {"name":"ff3_version"} 
[2020-04-22 09:35:19] local.DEBUG: Exists already, overwrite value. {"name":"ff3_version"} 
Updated version.
Application cache cleared!
Configuration cache cleared!
Configuration cached successfully!
Run chown on /mnt/cache/appdata/firefly-iii//storage
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.2.2!                                |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.14. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.14. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 22 09:35:20.441577 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.16 OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Apr 22 09:35:20.441602 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
`

**Comment by JC5** [comment]
It doesn't seem so. I still see no debug statements, and also no error. 

Can you refresh the page and see if the logs come up with anything?

**Comment by pape92** [comment]
Now the page doesnt open see screenshot
![Screenshot_1](https://user-images.githubusercontent.com/15344932/79958631-74009980-8483-11ea-9fa4-268a6cce2e61.png)

**Comment by JC5** [comment]
On Docker, that's weird! Delete the container and restart. That should fix it.

When your run docker commands like `docker exec -it ....` make sure you do it like this:

`docker --user www-data exec -it ...`
