### ISSUE TITLE
Transaction Splitting no longer works at all.

### ISSUE THREAD

**Issue by kairix-gh** [firefly-iii/firefly-iii#3862]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is:

Attempting to split any transaction results in an error 422 from the internal API. There isn't any validation errors or error message on the edit transaction form.

From browser console:
`PUT http://192.168.0.31:1000/api/v1/transactions/622?_token=UhzTlFoJcsh93c4YTAEv2gRGpIvtq50iib4V7UBE 422 (Unprocessable Entity)     edit_transaction.js?v=5.4.2:1 `

From log file:
`0.113 - - [26/Sep/2020:17:22:39 +0000] "PUT /api/v1/transactions/622?_token=UhzTlFoJcsh93c4YTAEv2gRGpIvtq50iib4V7UBE HTTP/1.1" 422 1135 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"`

**Steps to reproduce**
Split any transaction, either manually created or imported using the CSV Importer tool. **This can be reproduced on the demo site as well.**

**Extra info**
Latest version of Chrome

**Comment by niklas2810** [comment]
Hmmh, that's odd. Could you describe the steps you made on the demo site a litte bit more detailed? I was able to create a split transaction: https://demo.firefly-iii.org/transactions/show/463

**Comment by kairix-gh** [comment]
Sure - 

1. Click Actions -> Edit on a transaction
2. Click 'Add another split'
3. Fill in Description and Destination Account for the added split (Split 2/2).
4. Split the amount between each split
5. Fill in Description
6. Click 'Update transaction'

There aren't any validation errors on the form, so not really sure what's up.

**Comment by niklas2810** [comment]
@kairix-gh Is this the error badge you are seeing? ![Screenshot_20200926-204649_Firefox.jpg](https://user-images.githubusercontent.com/30748216/94348027-74f0b500-0039-11eb-927e-79a2a03f6b10.jpg)

**Comment by kairix-gh** [comment]
Yeah, I noticed that did pop up when I tried it a second time. Turns out, if you dismiss that warning because you had a validation error (like I had the first time - forgot the split description), it does not pop up again when the API returns error 422.

**Comment by anamaria85** [comment]
I have the same problem when splitting a transaction!

**Comment by kairix-gh** [comment]
Is there any update on this? This bug is also present on mobile as well.

**Comment by JC5** [comment]
Don't bump issues. Be patient.

**Comment by JC5** [comment]
Thanks all for waiting. I believe I've fixed this, and a fix is live on the [demo site](https://demo.firefly-iii.org/). I'd be grateful if you could check if this works as expected. If not, let me know.

**Comment by kairix-gh** [comment]
can confirm this is fixed for me on the demo site

**Comment by anamaria85** [comment]
On demo, fresh split, the error persists.
On demo, when editing an existing transaction and adding a split, works
On demo, when editing an existing transaction and adding a split, but selecting Store as a new transaction instead of updating, the error persists
![firefly-error](https://user-images.githubusercontent.com/6409346/94778681-5e968080-03ce-11eb-9938-7e06df40e347.png)

**Comment by JC5** [comment]
That seems to be a different error. When you create a withdrawal (top split) you can't create a transfer too (bottom split).

**Comment by anamaria85** [comment]
Sorry, my bad. Destination account from demo misled me
