### ISSUE TITLE
Autocomplete position in Chrome

### ISSUE THREAD

**Issue by Prandur** [firefly-iii/firefly-iii#3894]
**Bug description**
I am running Firefly III version 5.4.2, and my problem is:

When accessing the page on Chrome (85.0.4183.121) and editing a rule the autocomplete is positioned directly on the entry I'm editing: This makes editing problematic. The Screenshot is from the demo website. I tried to reproduce this with Firefox, but there its behaving correctly.
![image](https://user-images.githubusercontent.com/12172861/94991692-f6d66600-0584-11eb-8fd2-7a696d6eaba1.png)

**Steps to reproduce**
Edit a rule in Chrome (possibly on other autocomplete locations too)

**Extra info**
| Scope | Version |
| --- | --- |
| Firefly III | 5.4.2 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | e117024a-161c-4fba-893a-02c5ad73c577 |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | 10.0.0.26 |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2017-10-01 00:00:00 |
| User ID | 3 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 |

**Bonus points**

- :white_check_mark: I searched and nobody reported this bug before (at least I wasn't able to find another report)
- :no_entry: I have added a stack trace from my log files 
- :white_check_mark: I have added a screenshot.
- :white_check_mark: I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Nicely spotted. I pushed some updates to the code. Could you verify if this works as expected on the demo site?

**Comment by Prandur** [comment]
On Chrome it's still the same behavior. 
It appears to me that Chrome evaluates 'position: absolute' in a different manner than Firefox.

**Comment by JC5** [comment]
Works for me ™️ 

<img width="938" alt="Screenshot 2020-10-03 at 15 52 56" src="https://user-images.githubusercontent.com/5889984/94993330-c2ac7680-057f-11eb-958c-a9a85974ed2b.png">

**Comment by Prandur** [comment]
It works now for me too. Made sure that really everything is removed from the previous session.
