### ISSUE TITLE
Layout v2 doesn't jump to April 1st.

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#4575]
This is actually a "feature", not a bug as such. Check out: https://twitter.com/Firefly_III/status/1367074518536175618

Let me know what you would like Firefly III to do. But remember, Firefly III can't readily tell the difference between

- "it's the first day of a new period, but the range is still on the last period"
- "it's the first day of a new period, but the user set it on another perid on purpose"

**Comment by death2cupbots** [comment]
I think giving people a choice between defaulting to "Last 7 days" or "Last 30 days" would be pretty cool. I'd like to open the site and see last 30. I do miss having the month options on the calendar drop down: 
![image](https://user-images.githubusercontent.com/21091510/113357593-37cfed00-9312-11eb-9550-51b65d71659d.png)
Having a quick way to select "April" or "March" or whatever might make people happy too.

**Comment by JC5** [comment]
Indeed, I still have to add those :+1:

**Comment by JC5** [comment]
Done!

**Comment by death2cupbots** [comment]
So in 5.5.1 and 5.5.2, if I click on "Reset to Current period" it still defaults to "March 1 - March 31." In 5.5.1, I figured it was related to the time bug, but that's fixed at it's still happening. Is there a way for me to change how it views my "Current Period?"

**Comment by JC5** [comment]
It picks up the settings from v1. Mine is jumping to January 1st. I'll reopen this one and make sure it'll reset to *some* period 😁

**Comment by death2cupbots** [comment]
Weirdly enough, this only happens to me on Brave. It resets to April 2021 on Chrome on Windows and Firefox on Linux. Brave is still stuck in March.

**Comment by JC5** [comment]
It may be in your session still.
