### ISSUE TITLE
Support LDAP filter again

### ISSUE THREAD

**Issue by nebulade** [firefly-iii/firefly-iii#5133]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

With the new LDAP implementation from version 5.6 on, LDAP filters to search for users in the directory should be supported through `ADLDAP_AUTH_FILTER` according to https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication/#ldap

However setting this variable in the `.env` file is not taken into account. The filter seems to always be (&(objectclass=top)(objectclass=person)(objectclass=organizationalperson)(objectclass=inetorgperson)(username=<loginname>)) which is wrong in for example the Cloudron case.

### Solution

Support `ADLDAP_AUTH_FILTER` again. It seems like https://github.com/firefly-iii/firefly-iii/commit/0ee3941b43cb41a924aca16bcb89cb21be9a4c27 got accidentally lost due to the refactoring of the LDAP code.

**Comment by nebulade** [comment]
This came via https://github.com/firefly-iii/firefly-iii/issues/5109

**Comment by JC5** [comment]
Indeed, the LDAP filter was dropped. The library has changed significantly and i wasn't able to collect the necessary feedback through early releases. I'll pick it up as an enhancement. Be aware the new filter will probably something like `LDAP_AUTH_FILTER` (dropping the `AD`).

**Comment by JC5** [comment]
The `develop` Docker image as well as the `develop` branch on GitHub, now has a new option `LDAP_GROUP_FILTER`, which works [like this](https://github.com/firefly-iii/firefly-iii/blob/develop/.env.example#L188), based on [this documentation](https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#rules).

I appreciate your feedback!

**Comment by twicechild** [comment]
Hello,

Unfortunately I keep having the same issue. Maybe it's a different kind of thing not related with the filter option?

This is the log I get:

> 
> [2021-10-03T10:53:09.915947+00:00] local.INFO: AUDIT: User is trying to login using "" (192.168.x.x -> POST:https://wallet.grannysparlor.gr/login) [] [],
[2021-10-03 10:53:09] local.DEBUG: Installer middleware for URI https://wallet.mydomain.ad/login  ,
[2021-10-03 10:53:09] local.INFO: User is trying to login.  ,
[2021-10-03 10:53:09] local.DEBUG: User wishes to login using LDAP.  ,
[2021-10-03 10:53:09] local.DEBUG: Login data is valid.  ,
[2021-10-03 10:53:09] local.INFO: LDAP (ldap://192.168.40.230:389) - Operation: Binding - Username: CN=ldapread,OU=ITUSERS,DC=mydomain,DC=ad  ,
[2021-10-03 10:53:09] local.INFO: LDAP (ldap://192.168.40.230:389) - Operation: Search - Base DN: OU=GRANNYSUSERS,DC=grannysparlor,DC=ad - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\69\6e\65\74\6f\72\67\70\65\72\73\6f\6e)(sAMAccountName=\62\6c\61\63\6b\6e\61\73)) - Selected: (entryuuid,*) - Time Elapsed: 5.02  ,
[2021-10-03 10:53:09] local.INFO: LDAP (ldap://192.168.x.x:389) - Operation: Bound - Username: CN=ldapread,OU=ITUSERS,DC=mydomain,DC=ad  ,
[2021-10-03 10:53:09] local.WARNING: Login attempt failed.  ,
[2021-10-03T10:53:09.928324+00:00] local.INFO: AUDIT: Login failed. Attempt for user "blacknas" failed. (192.168.42.20 -> POST:https://wallet.mydomain.ad/login) [] [],
172.21.0.1 - - [03/Oct/2021:10:53:09 +0000] "POST /login HTTP/1.0" 302 2317 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"


I think the problem is in this line:
Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\69\6e\65\74\6f\72\67\70\65\72\73\6f\6e)(sAMAccountName=\62\6c\61\63\6b\6e\61\73))

I used the filter option in my env file like this:

LDAP_GROUP_FILTER="CN=owners,OU=GROUPS,DC=mydomain,DC=ad"

I could open a different issue if this is irrelevant.

Thank you!

**Comment by Expro** [comment]
Same issue here. Despite using develop tag and both env variables, logs shows hard-coded filter and LDAP authentication fails.

**Comment by JC5** [comment]
Hi guys, thanks for the feedback. I think I found the issue. I just pushed a new `develop` image (and the `develop` tag is also up to date. It adds some logging too.

I appreciate the feedback as always!

**Comment by Expro** [comment]
Either my image is not refreshing or changes did not successfully resolved this issue.

It would be nice if logs included build number so one can be sure which build is being ran.

**Comment by JC5** [comment]
Not a bad idea. In the mean time, the develop build is [just a few minutes old](https://hub.docker.com/repository/docker/fireflyiii/core/tags?page=1&ordering=last_updated&name=develop) but be sure to turn on [debug mode](https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode)

**Comment by JC5** [comment]
Latest build should auto-report the build number:

```
Now in entrypoint.sh for Firefly III
Script:       1.0.19 (2021-10-04)
User:         'root'
Group:        'root'
Working dir:  '/var/www/html'
Build number:  5
Build date:    10-04-2021 07:54:23 CEST
```

**Comment by Expro** [comment]
Thanks.

Unfortunately, this issue is still present. Logs shows following filter:

Operation: Search - Base DN: DC=expro,DC=name - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\69\6e\65\74\6f\72\67\70\65\72\73\6f\6e)(sAMAccountName=\65\78\70\72\6f)) 

While this is filter configured for this container:
        - name: LDAP_AUTH_FILTER
          value: "(memberOf=CN=People,CN=Users,DC=expro,DC=name)"
        - name: LDAP_GROUP_FILTER
          value: "CN=People,CN=Users,DC=expro,DC=name"

That's on correct image:
Script:       1.0.19 (2021-10-04)
User:         'root'
Group:        'root'
Working dir:  '/var/www/html'
Build number:  6
Build date:    04-10-2021 08:01:01 CEST

Rest of LDAP-relevant logs:

[2021-10-04 10:50:08] local.INFO: User is trying to login.
[2021-10-04 10:50:08] local.DEBUG: User wishes to login using LDAP.
[2021-10-04 10:50:08] local.DEBUG: Login data is valid.
[2021-10-04 10:50:08] local.INFO: LDAP (ldap://domain.expro.name:389) - Operation: Binding - Username: CN=Bind,CN=Users,DC=expro,DC=name
[2021-10-04 10:50:08] local.INFO: LDAP (ldap://domain.expro.name:389) - Operation: Bound - Username: CN=Bind,CN=Users,DC=expro,DC=name
[2021-10-04 10:50:08] local.INFO: LDAP (ldap://domain.expro.name:389) - Operation: Search - Base DN: DC=expro,DC=name - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\69\6e\65\74\6f\72\67\70\65\72\73\6f\6e)(sAMAccountName=\65\78\70\72\6f)) - Selected: (entryuuid,*) - Time Elapsed: 9.56
[2021-10-04 10:50:08] local.WARNING: Login attempt failed.
[2021-10-04T10:50:08.535860+02:00] local.INFO: AUDIT: Login failed. Attempt for user "expro" failed. (192.168.1.102 -> POST:https://fireflyiii.expro.name/login) [] []

**Comment by JC5** [comment]
According to the documentation of the library I'm using, the group filter will not even be tried until authentication is correct. So I believe something there is broken still.

"Login data is valid" refers to the submission, "Login attempt failed" tells me that the LDAP server doesn't seem to accept the login. 

Is the `LDAP_AUTH_FIELD` field correct?

**Comment by Expro** [comment]
> Is the LDAP_AUTH_FIELD field correct?

I think it is. Initially all settings were copied from other app that already has LDAP authentication working correctly, but I have also tried other attributes (samaccountname, distringuishedname, mail).

**Comment by Expro** [comment]
I wonder if this line in logs is indicating something:

`[2021-10-04T11:42:00.708033+02:00] local.INFO: AUDIT: User is trying to login using "" (192.168.1.102 -> POST:https://fireflyiii.expro.name/login) [] []`

Perhaps something (username?) is not being forwarded somewhere to LDAP server if it is not appearing in logs ("" is empty).

**Comment by JC5** [comment]
Mmm, good detective work! I'll pick it this up later today :+1:

**Comment by Expro** [comment]
Another pointer: neither LDAP_GROUP_FILTER nor LDAP_AUTH_FILTER is present in source code, according to GitHub search engine. No wonder they are not affecting filter in resulting binaries.

**Comment by JC5** [comment]
Yeah GitHub search sucks. `LDAP_AUTH_FILTER` is currently not being used, but `LDAP_GROUP_FILTER` is.

- https://github.com/firefly-iii/firefly-iii/blob/develop/app/Ldap/Rules/UserDefinedRule.php#L20
- https://github.com/firefly-iii/firefly-iii/blob/develop/config/ldap.php#L40

**Comment by JC5** [comment]
Unfortunately that wasn't it. The search continues. 5.6.2 will go out this weekend but apart from the filter (which may not work for you yet) no other changes.

**Comment by nebulade** [comment]
Great, let us know if you want access to a test Cloudron, to test this against our built-in LDAP server yourself, otherwise I will of course once you have some new state.

**Comment by JC5** [comment]
I would appreciate that, thanks! 

I've been playing around with rules and scopes this past week but no luck so far. I'll keep you guys posted when i have something!

**Comment by JC5** [comment]
I pushed some improvements to the develop branch. Filtering through the base DN works. It should be the main way to filter users.

I can't be sure about the "extra" filters, please see [.env.exampe](https://github.com/firefly-iii/firefly-iii/blob/develop/.env.example#L208) and give me your feedback.

Thanks for your support so far!

**Comment by Expro** [comment]
Filters are still broken:

`[2021-10-30 20:43:51] local.INFO: LDAP (ldap://domain.expro.name:389) - Operation: Binding - Username: CN=Bind,CN=Users,DC=expro,DC=name
[2021-10-30 20:43:51] local.INFO: LDAP (ldap://domain.expro.name:389) - Operation: Bound - Username: CN=Bind,CN=Users,DC=expro,DC=name
[2021-10-30 20:43:51] local.INFO: LDAP (ldap://domain.expro.name:389) - Operation: Search - Base DN: DC=expro,DC=name - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\75\73\65\72)(mail=\65\78\70\72\6f)(!(objectclass=\63\6f\6d\70\75\74\65\72))) - Selected: (objectguid,*) - Time Elapsed: 47.65`

**Comment by JC5** [comment]
I have no server to test this on, sorry.

**Comment by twicechild** [comment]
Hello, I finally had some time to catch up...

This is my log:

> wallet          | [2021-11-02T16:44:11.864492+00:00] local.INFO: AUDIT: User is trying to login using "" (192.168.x.x -> POST:https://wallet.grannysparlor.gr/login) [] []
wallet          | [2021-11-02 16:44:11] local.INFO: User is trying to login.
wallet          | [2021-11-02 16:44:11] local.DEBUG: User wishes to login using LDAP.
wallet          | [2021-11-02 16:44:11] local.DEBUG: Login data is valid.
wallet          | [2021-11-02 16:44:11] local.INFO: LDAP (ldap://192.168.xx.xx:389) - Operation: Binding - Username: CN=ldapread,OU=ITUSERS,DC=grannysparlor,DC=ad
wallet          | [2021-11-02 16:44:11] local.INFO: LDAP (ldap://192.168.xx.xx:389) - Operation: Bound - Username: CN=ldapread,OU=ITUSERS,DC=grannysparlor,DC=ad
wallet          | [2021-11-02 16:44:11] local.INFO: LDAP (ldap://192.168.xx.xx:389) - Operation: Search - Base DN: OU=GRANNYSUSERS,DC=grannysparlor,DC=ad - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\75\73\65\72)(sAMAccountName=\62\6c\61\63\6b\6e\61\73)(!(objectclass=\63\6f\6d\70\75\74\65\72))) - Selected: (objectguid,*) - Time Elapsed: 6.61
wallet          | [2021-11-02 16:44:11] local.INFO: User [Alexios Antilope] has been successfully discovered for authentication.
wallet          | [2021-11-02 16:44:11] local.INFO: Object with name [Alexios Antilope] is being synchronized.
wallet          | [2021-11-02 16:44:11] local.ERROR: Exception is: {"class":"TypeError","errorMessage":"FireflyIII\\Ldap\\AttributeHandler::handle(): Argument #1 ($ldap) must be of type LdapRecord\\Models\\OpenLDAP\\User, LdapRecord\\Models\\ActiveDirectory\\User given, called in \/var\/www\/html\/vendor\/directorytree\/ldaprecord-laravel\/src\/Import\/Hydrators\/AttributeHydrator.php on line 18","time":"Tue, 02 Nov 2021 16:44:11 +0000","file":"\/var\/www\/html\/app\/Ldap\/AttributeHandler.php","line":39,"code":0,"version":"5.6.2","url":"https:\/\/wallet.grannysparlor.gr\/login","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko\/20100101 Firefox\/93.0","json":true}
wallet          | [2021-11-02 16:44:11] local.ERROR: Exception when mailing: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
wallet          | [2021-11-02 16:44:11] local.ERROR: FireflyIII\Ldap\AttributeHandler::handle(): Argument #1 ($ldap) must be of type LdapRecord\Models\OpenLDAP\User, LdapRecord\Models\ActiveDirectory\User given, called in /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Hydrators/AttributeHydrator.php on line 18 {"exception":"[object] (TypeError(code: 0): FireflyIII\\Ldap\\AttributeHandler::handle(): Argument #1 ($ldap) must be of type LdapRecord\\Models\\OpenLDAP\\User, LdapRecord\\Models\\ActiveDirectory\\User given, called in /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Hydrators/AttributeHydrator.php on line 18 at /var/www/html/app/Ldap/AttributeHandler.php:39)

and my env file:

> AUTHENTICATION_GUARD=ldap
LDAP_DIALECT=ActiveDirectory
LDAP_HOST=192.168.xx.xx
LDAP_PORT=389
LDAP_TIMEOUT=5
LDAP_BASE_DN="OU=GRANNYSUSERS,DC=grannysparlor,DC=ad"
LDAP_SSL=false
LDAP_TLS=false
LDAP_USERNAME="CN=ldapread,OU=ITUSERS,DC=grannysparlor,DC=ad"
LDAP_PASSWORD=secret
LDAP_AUTH_FIELD=sAMAccountName

If I understand it correctly. It binds successfully, finds the user and then get a bit confused because this is not an OpenLDAP. Unfortunatelly I don't have an OpenLDAP server to test this.

@JC5 I know this might sound weird but I could have an ActiveDirectory brought up (with a simple user and group) so you can do some tests. Only "problem" is that I just have a home-lab. I'll have to figure out how to give you access. Just tell me if you are interested.

**Comment by JC5** [comment]
Thanks for letting me know. I guess that's a bug on my end, picking up the wrong class somewhere. I'll be in touch (probably over the weekend though) when I have a fix.

**Comment by nebulade** [comment]
I tried to debug this also further, but for some reason I am not able to see any of the debugs from https://github.com/firefly-iii/firefly-iii/blob/develop/app/Ldap/Rules/UserDefinedRule.php#L25 with a build from the `develop` branch

The env file contains:
```
APP_LOG_LEVEL=debug
AUTHENTICATION_GUARD=ldap

LDAP_DIALECT=OpenLDAP
LDAP_EXTRA_FILTER="(objectclass=user)"
LDAP_HOST=${CLOUDRON_LDAP_SERVER}
LDAP_PORT=${CLOUDRON_LDAP_PORT}
LDAP_TIMEOUT=5
LDAP_SSL=false
LDAP_TLS=false

LDAP_BASE_DN="${CLOUDRON_LDAP_USERS_BASE_DN}"
LDAP_USERNAME="${CLOUDRON_LDAP_BIND_DN}"
LDAP_PASSWORD="${CLOUDRON_LDAP_BIND_PASSWORD}"

LDAP_AUTH_FIELD=username
```

Essentially all the debug logs I get for a login attempt are:
```
[2021-11-10 15:15:48] local.DEBUG: Installer middleware for URI https://fire.nebulon.space/login  
[2021-11-10T15:15:48.037649+01:00] local.INFO: AUDIT: User is trying to login using "" (94.134.18.77 -> POST:https://fire.nebulon.space/login) [] []
[2021-11-10 15:15:48] local.INFO: User is trying to login.  
[2021-11-10 15:15:48] local.DEBUG: User wishes to login using LDAP.  
[2021-11-10 15:15:48] local.DEBUG: Login data is valid.  
[2021-11-10 15:15:48] local.INFO: LDAP (ldap://172.18.0.1:3002) - Operation: Binding - Username: cn=09c03f50-5fcc-4d97-94a0-fff8d76f3b9d,ou=apps,dc=cloudron  
[2021-11-10 15:15:48] local.INFO: LDAP (ldap://172.18.0.1:3002) - Operation: Bound - Username: cn=09c03f50-5fcc-4d97-94a0-fff8d76f3b9d,ou=apps,dc=cloudron  
[2021-11-10 15:15:48] local.INFO: LDAP (ldap://172.18.0.1:3002) - Operation: Search - Base DN: ou=users,dc=cloudron - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\69\6e\65\74\6f\72\67\70\65\72\73\6f\6e)(username=\6e\65\62\75\6c\6f\6e)) - Selected: (entryuuid,*) - Time Elapsed: 9.51  
[2021-11-10 15:15:48] local.WARNING: Login attempt failed.  
[2021-11-10T15:15:48.050800+01:00] local.INFO: AUDIT: Login failed. Attempt for user "nebulon" failed. (94.134.18.77 -> POST:https://fire.nebulon.space/login) [] []
172.18.0.1 - - [10/Nov/2021:14:15:48 +0000] "POST /login HTTP/1.1" 302 2270 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
[2021-11-10 15:15:48] local.DEBUG: Installer middleware for URI https://fire.nebulon.space/login  
[2021-11-10T15:15:48.341766+01:00] local.INFO: AUDIT: Show login form (1.1). (94.134.18.77 -> GET:https://fire.nebulon.space/login) [] []
[2021-11-10 15:15:48] local.DEBUG: User wishes to login using LDAP.  
172.18.0.1 - - [10/Nov/2021:14:15:48 +0000] "GET /login HTTP/1.1" 200 3572 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
172.18.0.1 - - [10/Nov/2021:14:15:49 +0000] "GET /serviceworker.js?v=5.6.2 HTTP/1.1" 200 1224 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
```

I feel I am missing something obvious to enable?

**Comment by JC5** [comment]
`[2021-11-10 15:15:48] local.WARNING: Login attempt failed.  `

I'm sure your password is correct of course, but there's not much more to report than this.

**Comment by nebulade** [comment]
Ok will have to debug further then, I am no php expert, but despite the recent upstream changes, the search filter, which I can see on the LDAP server side, after the successful bind operation, is still very much wrong for non ActiveDirectory, which is why it also returns no records. Thus my question about missing something obvious in the configs to not hit the OpenLDAP path.

**Comment by vcrazyV** [comment]
Hi. I thing i have simular problem after if use `LDAP_EXTRA_FILTER` in 5.6.4
if config without LDAP_EXTRA_FILTER login works fine. But if config like this login does't work:
```
LDAP_DIALECT=OpenLDAP
LDAP_HOST=ds.local
LDAP_PORT=389
LDAP_TIMEOUT=5
LDAP_BASE_DN="dc=server,dc=ds,dc=local"

# SSL/TLS settings
LDAP_SSL=false
LDAP_TLS=false

LDAP_USERNAME="uid=root,cn=users,dc=server,dc=ds,dc=local"
LDAP_PASSWORD="secret"

LDAP_AUTH_FIELD=uid
LDAP_EXTRA_FILTER="memberOf=cn=firefly-user,cn=groups,dc=server,dc=ds,dc=local"
ADLDAP_SYNC_FIELD=mail
```
I trying many configuration in filter:
`(memberOf=cn=firefly-user,cn=groups,dc=server,dc=ds,dc=local)`
`memberOf=cn=firefly-user,cn=groups,dc=server,dc=ds,dc=local`
`cn=firefly-user,cn=groups,dc=server,dc=ds,dc=local`

got result: 
```
[2021-11-18 22:44:23] local.INFO: User is trying to login.  
[2021-11-18 22:44:23] local.DEBUG: User wishes to login using LDAP.  
[2021-11-18 22:44:23] local.DEBUG: Login data is valid.  
[2021-11-18 22:44:23] local.INFO: LDAP (ldap://ds.local:389) - Operation: Binding - Username: uid=root,cn=users,dc=server,dc=ds,dc=local  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Bound - Username: uid=root,cn=users,dc=server,dc=ds,dc=local  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Search - Base DN: dc=server,dc=ds,dc=local - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\69\6e\65\74\6f\72\67\70\65\72\73\6f\6e)(uid=\76\69\6b\74\6f\72)) - Selected: (entryuuid,*) - Time Elapsed: 778.68  
[2021-11-18 22:44:24] local.INFO: User [viktor] has been successfully discovered for authentication.  
[2021-11-18 22:44:24] local.INFO: Object with name [viktor] is being synchronized.  
[2021-11-18 22:44:24] local.INFO: Object with name [viktor] has been successfully synchronized.  
[2021-11-18 22:44:24] local.INFO: User [viktor] is authenticating.  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Attempting - Username: uid=viktor,cn=users,dc=server,dc=ds,dc=local  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Binding - Username: uid=viktor,cn=users,dc=server,dc=ds,dc=local  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Bound - Username: uid=viktor,cn=users,dc=server,dc=ds,dc=local  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Passed - Username: uid=viktor,cn=users,dc=server,dc=ds,dc=local  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Binding - Username: uid=root,cn=users,dc=server,dc=ds,dc=local  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Bound - Username: uid=root,cn=users,dc=server,dc=ds,dc=local  
[2021-11-18 22:44:24] local.DEBUG: UserDefinedRule with extra filter "memberOf=cn=firefly-user,cn=groups,dc=server,dc=ds,dc=local"  
[2021-11-18 22:44:24] local.DEBUG: Extra filter is not empty, continue.  
[2021-11-18 22:44:24] local.DEBUG: Will use dialect group class "LdapRecord\Models\OpenLDAP\Group"  
[2021-11-18 22:44:24] local.DEBUG: UserDefinedRule: Head is "memberof"  
[2021-11-18 22:44:24] local.DEBUG: UserDefinedRule: Will return if user exists in group.  
[2021-11-18 22:44:24] local.INFO: LDAP (ldap://ds.local:389) - Operation: Read - Base DN: dc=server,dc=ds,dc=local - Filter: (&(objectclass=\74\6f\70)(objectclass=\67\72\6f\75\70\6f\66\75\6e\69\71\75\65\6e\61\6d\65\73)(objectclass=*)) - Selected: (entryuuid,*) - Time Elapsed: 1.04  
[2021-11-18 22:44:24] local.ERROR: Exception is: {"class":"LdapRecord\\Models\\ModelNotFoundException","errorMessage":"No LDAP query results for filter: [(&(objectclass=top)(objectclass=groupofuniquenames)(objectclass=*))] in: [memberOf=cn=firefly-user,cn=groups,dc=server,dc=ds,dc=local]","time":"Thu, 18 Nov 2021 22:44:24 +0300","file":"\/var\/www\/html\/vendor\/directorytree\/ldaprecord\/src\/Query\/ObjectNotFoundException.php","line":33,"code":0,"version":"5.6.4","url":"http:\/\/ds.local:32794\/login","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/96.0.4664.45 Safari\/537.36","json":true}  

```

In previos version 5.6.2 config was and work fine:
```
LDAP_HOST=ds.local
LDAP_PORT=389
LDAP_TIMEOUT=5
LDAP_BASE_DN="dc=server,dc=ds,dc=local"

# SSL/TLS settings
LDAP_SSL=false
LDAP_TLS=false

LDAP_USERNAME="uid=root,cn=users,dc=server,dc=ds,dc=local"
LDAP_PASSWORD="secret"

LDAP_AUTH_FIELD=uid
ADLDAP_AUTH_FILTER="(memberOf=cn=firefly-user,cn=groups,dc=server,dc=ds,dc=local)"
ADLDAP_SYNC_FIELD=mail
```

@JC5 i need to create new bug or can continue here?
Maybe it just my configuration mistake :(

**Comment by gramakri** [comment]
Another Cloudron package maintainer here. I managed to get the LDAP to work (atleast with Cloudron). Wanted to put a few notes here, in case it helps others:

* `LDAP_DIALECT` must now be set in env file. This can be OpenLDAP or ActiveDirectory or FreeIPA based on your setup. Cloudron uses OpenLDAP

* Unlike before, a "filter" is hardcoded in the new LDAP module. For example, it always looks for objectClasses to be https://github.com/DirectoryTree/LdapRecord/blob/master/src/Models/OpenLDAP/User.php#L33 . In Cloudrons case, we just fixed our LDAP server to provide those object classes. As a temporary measure in our package (till the new release is out), I just patched the ldap module by deleting those LDAP classes. See https://git.cloudron.io/cloudron/firefly-iii-app/-/blob/master/Dockerfile#L27

@JC5 atleast the original bug reported by @nebulade is now fixed. So, you can close this if you like.

**Comment by stevebauman** [comment]
Hi @JC5, I'm happy to help! Still subscribed to this thread 👍 

Instead of using the `OpenLdap\Group`/`ActiveDirectory\Group` or `FreeIPA\Group`, you can use the global `Entry` model instead which contains [no object classes](https://github.com/DirectoryTree/LdapRecord/blob/master/src/Models/Entry.php). This means calling `Entry::get()` will query for *all* object types on the LDAP server, below the users base DN (if you'd prefer to avoid specifying the ldap "dialect").

For example:

**Instead of**:
https://github.com/firefly-iii/firefly-iii/blob/4e2d5fe1663994e4cd26532381761157a1acd2e4/app/Ldap/Rules/UserDefinedRule.php#L59
```php
$groupClass = config('ldap.dialect') === 'OpenLDAP' ? $openLDAP : $activeDirectory;
```

You could do:

```php
$model = \LdapRecord\Models\Entry::class;

// ...

if (!DistinguishedName::isValid($extraFilter)) {
    Log::debug('UserDefinedRule: Is not valid DN');

    return $this->user->groups()->recursive()->exists($model::findByAnrOrFail($extraFilter));
}

// ...
```

This would resolve issues (like @gramakri) has since not all OpenLDAP installations are the same. Some may have different schemas using different object classes. The built-in models may not suite all server setups perfectly (unfortunately).

I hope this helps! Let me know if you have any further questions or need help with implementation 👍

**Comment by stevebauman** [comment]
Also I should mention, these models have their object classes as `public static`. The object classes on the built-in models can be overridden prior to executing a query on the model, so you could provide a config value to simply override these:

```php
use LdapRecord\Models\ActiveDirectory\Group;

Group::$objectClasses = config(
    'ldap.object_classes', // Configured classes.
    Group::$objectClasses, // Default value.
);

$groups = Group::get();
```

Keep in mind this could break some of the models methods if certain objects are returned that are not groups (in the above case). Object classes are what define an object type in LDAP and what attributes / methods are availble.

**Comment by gramakri** [comment]
@stevebauman Sorry, maybe I didn't explain the problem properly (or maybe I don't understand your solution properly). The issue is that the search base is hardcoded. When doing a search, the query sent to the server is `filter="(&(objectClass=top)(objectClass=person)(objectClass=organizationalPerson)(objectClass=inetOrgPerson)(uid=USERNAME))` . These object classes like `top` cause issues in filtering (atleast for our LDAP server anyway). You can also see https://github.com/firefly-iii/firefly-iii/discussions/5533 for another such report.

Note that the above is not to do with groups etc. This is just the initial LDAP search to find the user dn before the user/password bind. Can you tell me if your solution is trying to solve the above issue? (I will try to understand it better :-) )

**Comment by stevebauman** [comment]
> The issue is that the search base is hardcoded.

> These object classes like `top` cause issues in filtering (atleast for our LDAP server anyway). You can also see #5533 for another such report.

Right -- these can be overridden at any time using the solution I posted above. The `$objectClasses` in each model are used for constructing the filter so objects of proper type are returned.

> Note that the above is not to do with groups etc. This is just the initial LDAP search to find the user dn before the user/password bind. Can you tell me if your solution is trying to solve the above issue? (I will try to understand it better, unfortunately I am not a PHP dev... :-) )

You can utilize the above solution to alter the object classes on whichever model is configured for LDAP authentication in firefly. This gives you full control over the LDAP filter that is sent to your server to retrieve objects. Ex:

```php
use LdapRecord\Models\OpenLDAP\User;

// Default object classes:
// array(4) {
//   "top"
//   "person"
//   "organizationalperson"
//   "inetorgperson"
// }
var_dump(User::$objectClasses);

// The object classes are used to generate the query:
// (&(objectclass=top)(objectclass=person)(objectclass=organizationalperson)(objectclass=inetorgperson))
var_dump(User::query()->getUnescapedQuery());

// Change the object classes:
User::$objectClasses = ['foo', 'bar'];

// (&(objectclass=foo)(objectclass=bar))
var_dump(User::query()->getUnescapedQuery());
```

**Comment by JC5** [comment]
I skipped over this one for a few weeks. With the solution proposed by Steve and the necessary changes to Cloudron I'm going to close this. I'll keep it in my bookmarks in case relevant issues appear. Thanks for the excellent code examples and feedback :+1:

**Comment by stevebauman** [comment]
Happy to help @JC5!
