### ISSUE TITLE
Nordigen data conversion fails

### ISSUE THREAD

**Issue by Vercety87** [firefly-iii/firefly-iii#5407]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi,

I’ve an issue with the data importer.

When I try to import via Nordigen, bank « Boursorama Banque », I got this error :
```
The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :(

Message(s)
Line #0:
Parsed 0 Nordigen transactions for further processing.
Filtered down from 0 (possibly duplicate) entries to 0 unique transactions.
```

### Expected behaviour

The data conversion should convert the data from Nordigen.

### Debug information

Debug information generated at 2021-12-19 17:44:20 Europe/Amsterdam for Firefly III Data Importer version **0.4.0**.

| Scope | Version |
| --- | --- |
| FIDI | 0.4.0 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Paris |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15 |

**Comment by JC5** [comment]
> Please check the log files. 

1. I need those to debug this.
2. Since you're running a `develop` version, please make sure you pull the latest version. It got some updates today.

**Comment by Vercety87** [comment]
Hi,

Thanks for the help, just running with the latest version but same problem.

```
Debug information generated at 2021-12-19 18:00:32 Europe/Amsterdam for Firefly III Data Importer version **0.3.0**.

| Scope | Version |
| --- | --- |
| FIDI | 0.3.0 |
| PHP | 8.0.12 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Paris |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15 |
```

Here the log :

```
[2021-12-19 18:20:52] production.DEBUG: Return redirect to "http://192.168.0.80:8087/import/convert"  
[2021-12-19 18:20:52] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-19 18:20:52] production.DEBUG: Now in App\Http\Controllers\Import\ConversionController::index  
[2021-12-19 18:20:52] production.DEBUG: Will now verify configuration content.  
[2021-12-19 18:20:52] production.DEBUG: NO role info in config, will send you back to roles..  
[2021-12-19 18:20:52] production.DEBUG: NO mapping in file, will send you back to mapping..  
[2021-12-19 18:20:52] production.DEBUG: Going to generate conversion routine identifier.  
[2021-12-19 18:20:52] production.DEBUG: Attempt #1 results in "conv-71dnS8Hhrl93"  
[2021-12-19 18:20:52] production.INFO: Job identifier is "conv-71dnS8Hhrl93"  
[2021-12-19 18:20:52] production.DEBUG: Conversion routine manager identifier is "conv-71dnS8Hhrl93"  
[2021-12-19 18:20:52] production.DEBUG: Stored "conv-71dnS8Hhrl93" under "conversion_job_id"  
[2021-12-19 18:20:53] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-19 18:20:53] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:53] production.DEBUG: Now in startOrFindConversion(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:53] production.DEBUG: Try to see if file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:53] production.DEBUG: File does not exist or error, create a new one.  
[2021-12-19 18:20:53] production.DEBUG: Return status. {"status":"waiting_to_start","errors":[],"warnings":[],"messages":[]} 
[2021-12-19 18:20:54] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-19 18:20:54] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::start  
[2021-12-19 18:20:54] production.DEBUG: Now in startOrFindConversion(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:54] production.DEBUG: Try to see if file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Status file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Now in setConversionStatus(conv_running)  
[2021-12-19 18:20:54] production.DEBUG: Found "conv-71dnS8Hhrl93" in the session  
[2021-12-19 18:20:54] production.DEBUG: Now in startOrFindConversion(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:54] production.DEBUG: Try to see if file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Status file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Now in storeConversionStatus(conv-71dnS8Hhrl93): conv_running  
[2021-12-19 18:20:54] production.DEBUG: Now in App\Services\Nordigen\Conversion\RoutineManager::start  
[2021-12-19 18:20:54] production.DEBUG: Call transaction processor download.  
[2021-12-19 18:20:54] production.DEBUG: Now in App\Services\Nordigen\Conversion\Routine\TransactionProcessor::download  
[2021-12-19 18:20:54] production.DEBUG: Done with download  
[2021-12-19 18:20:54] production.DEBUG: Generating Firefly III transactions.  
[2021-12-19 18:20:54] production.DEBUG: Going to collect all target accounts from Firefly III.  
[2021-12-19 18:20:54] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-19 18:20:54] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:54] production.DEBUG: Now in startOrFindConversion(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:54] production.DEBUG: Try to see if file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Status file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Collected 0 accounts.  
[2021-12-19 18:20:54] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken  
[2021-12-19 18:20:54] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens  
[2021-12-19 18:20:54] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2021-12-19 18:20:54] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2021-12-19 18:20:54] production.DEBUG: Nordigen token is valid until 2021-12-20 18:20:04  
[2021-12-19 18:20:54] production.DEBUG: Nordigen token is valid.  
[2021-12-19 18:20:54] production.DEBUG: Going to collect account information from Nordigen.  
[2021-12-19 18:20:54] production.DEBUG: Now generate transactions.  
[2021-12-19 18:20:54] production.DEBUG: Add message on index #0 (line no. 1): Parsed 0 Nordigen transactions for further processing.  
[2021-12-19 18:20:54] production.DEBUG: Now in storeConversionStatus(conv-71dnS8Hhrl93): conv_running  
[2021-12-19 18:20:54] production.DEBUG: Done parsing transactions.  
[2021-12-19 18:20:54] production.DEBUG: Generated 0 Firefly III transactions.  
[2021-12-19 18:20:54] production.DEBUG: Add message on index #0 (line no. 1): Filtered down from 0 (possibly duplicate) entries to 0 unique transactions.  
[2021-12-19 18:20:54] production.DEBUG: Now in storeConversionStatus(conv-71dnS8Hhrl93): conv_running  
[2021-12-19 18:20:54] production.DEBUG: Filtered down to 0 Firefly III transactions.  
[2021-12-19 18:20:54] production.ERROR: Zero transactions!  
[2021-12-19 18:20:54] production.DEBUG: Now in setConversionStatus(conv_errored)  
[2021-12-19 18:20:54] production.DEBUG: Found "conv-71dnS8Hhrl93" in the session  
[2021-12-19 18:20:54] production.DEBUG: Now in startOrFindConversion(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:54] production.DEBUG: Try to see if file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Status file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Now in storeConversionStatus(conv-71dnS8Hhrl93): conv_errored  
[2021-12-19 18:20:54] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-19 18:20:54] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:54] production.DEBUG: Now in startOrFindConversion(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:54] production.DEBUG: Try to see if file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:54] production.DEBUG: Status file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:55] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-19 18:20:55] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:55] production.DEBUG: Now in startOrFindConversion(conv-71dnS8Hhrl93)  
[2021-12-19 18:20:55] production.DEBUG: Try to see if file exists for conversion "conv-71dnS8Hhrl93".  
[2021-12-19 18:20:55] production.DEBUG: Status file exists for conversion "conv-71dnS8Hhrl93".  
```

**Comment by JC5** [comment]
Looks like there’s nothing to import.

**Comment by JC5** [comment]
I'll see if I can replicate this tomorrow. At least it should show a better error!

**Comment by Vercety87** [comment]
Thanks,

I just noticed in the data importer tools, that in front of all my bank accounts, there’s nothing in « Firefly III » select list.

[https://share.icloud.com/photos/0857im71hTQAe767l5GqbPK3A](url)

But below I can see my Firefly III account.

Do you think I need to be able to select my FF III account in front of my bank account ?

**Comment by JC5** [comment]
Could you upload the screenshot in a reply please? Just drag and drop

**Comment by JC5** [comment]
Do you have Firefly III asset accounts?

**Comment by Vercety87** [comment]
> Do you have Firefly III asset accounts?

Yes I have one asset account in my Firefly III.

Here the screenshot :

![1711BF47-A97E-4959-9CAE-DD2EE1185DA8](https://user-images.githubusercontent.com/44375309/146688919-cabf4bdd-57b4-4153-b5da-8f9e0f520c19.jpeg)

**Comment by Vercety87** [comment]
In complement, when I use the data importer with a CSV file, there’s no problem with the tool.

**Comment by FredericMa** [comment]
I'm having the same issue, also the drop down is empty:
![image](https://user-images.githubusercontent.com/7840263/146788015-b2cd03a5-1066-48b8-966f-fe79d371a1d9.png)

**Comment by JC5** [comment]
Found the issue, a fix is underway!

**Comment by JC5** [comment]
I pushed a fix to the develop image and I would appreciate your feedback.

**Comment by Vercety87** [comment]
Thanks, I will try by the end of the day and provide you my feedback

**Comment by Vercety87** [comment]
The problem is still present :

Debug information generated at 2021-12-20 21:24:14 Europe/Amsterdam for Firefly III Data Importer version **0.4.0**.

```
| Scope | Version |
| --- | --- |
| FIDI | 0.4.0 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Paris |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15 |

```

```
Truncated from this point <----|::getFullName()  
[2021-12-20 21:18:47] production.DEBUG: Return getName(): "xxxxxxxxxxxx"  
[2021-12-20 21:18:47] production.DEBUG: isReadyForNordigenStep("configuration")  
[2021-12-20 21:18:47] production.DEBUG: Method App\Http\Controllers\Import\ConfigurationController::phpDate  
[2021-12-20 21:19:19] production.DEBUG: isReadyForNordigenStep("configuration")  
[2021-12-20 21:19:19] production.DEBUG: Now running App\Http\Controllers\Import\ConfigurationController::postIndex  
[2021-12-20 21:19:19] production.DEBUG: Now in updateDateRange()  
[2021-12-20 21:19:19] production.DEBUG: Range is "range", both will be created from a string.  
[2021-12-20 21:19:19] production.DEBUG: dateNotBefore is now "2021-12-01", dateNotAfter is "2021-12-20"  
[2021-12-20 21:19:19] production.DEBUG: storeContent: Stored 970 bytes in file "xxxxxxxxxx"  
[2021-12-20 21:19:19] production.DEBUG: Configuration debug: Connection ID is "0"  
[2021-12-20 21:19:19] production.DEBUG: isReadyForNordigenStep("define-roles")  
[2021-12-20 21:19:19] production.DEBUG: redirectToCorrectNordigenStep("define-roles")  
[2021-12-20 21:19:19] production.DEBUG: Return redirect to "http://192.168.0.80:8087/import/mapping"  
[2021-12-20 21:19:19] production.DEBUG: isReadyForNordigenStep("map")  
[2021-12-20 21:19:19] production.DEBUG: Return false, not yet ready for step [2].  
[2021-12-20 21:19:19] production.DEBUG: redirectToCorrectNordigenStep("map")  
[2021-12-20 21:19:19] production.DEBUG: Is ready for conversion, so send to conversion.  
[2021-12-20 21:19:19] production.DEBUG: Return redirect to "http://192.168.0.80:8087/import/convert"  
[2021-12-20 21:19:19] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:19:19] production.DEBUG: Now in App\Http\Controllers\Import\ConversionController::index  
[2021-12-20 21:19:19] production.DEBUG: Will now verify configuration content.  
[2021-12-20 21:19:19] production.DEBUG: NO role info in config, will send you back to roles..  
[2021-12-20 21:19:19] production.DEBUG: NO mapping in file, will send you back to mapping..  
[2021-12-20 21:19:19] production.DEBUG: Conversion routine manager identifier is "conv-3PAhLdLwEvVo"  
[2021-12-20 21:19:19] production.DEBUG: Stored "conv-3PAhLdLwEvVo" under "conversion_job_id"  
[2021-12-20 21:19:19] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:19:19] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:19] production.DEBUG: Now in startOrFindConversion(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:19] production.DEBUG: Try to see if file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:19] production.DEBUG: Status file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:20] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:19:20] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::start  
[2021-12-20 21:19:20] production.DEBUG: Now in startOrFindConversion(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:20] production.DEBUG: Try to see if file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:20] production.DEBUG: Status file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:20] production.DEBUG: Now in setConversionStatus(conv_running)  
[2021-12-20 21:19:20] production.DEBUG: Found "conv-3PAhLdLwEvVo" in the session  
[2021-12-20 21:19:20] production.DEBUG: Now in startOrFindConversion(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:20] production.DEBUG: Try to see if file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:20] production.DEBUG: Status file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:20] production.DEBUG: Now in storeConversionStatus(conv-3PAhLdLwEvVo): conv_running  
[2021-12-20 21:19:20] production.DEBUG: Now in App\Services\Nordigen\Conversion\RoutineManager::start  
[2021-12-20 21:19:20] production.DEBUG: Call transaction processor download.  
[2021-12-20 21:19:20] production.DEBUG: Now in App\Services\Nordigen\Conversion\Routine\TransactionProcessor::download  
[2021-12-20 21:19:20] production.DEBUG: Done with download  
[2021-12-20 21:19:20] production.DEBUG: Generating Firefly III transactions.  
[2021-12-20 21:19:20] production.DEBUG: Going to collect all target accounts from Firefly III.  
[2021-12-20 21:19:20] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:19:20] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:20] production.DEBUG: Now in startOrFindConversion(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:20] production.DEBUG: Try to see if file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:20] production.DEBUG: Status file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:21] production.DEBUG: Collected account nr "xxxxxxxx." (asset) under ID #6  
[2021-12-20 21:19:21] production.DEBUG: Collected 1 accounts. {"xxxxxxx.":6} 
[2021-12-20 21:19:21] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken  
[2021-12-20 21:19:21] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens  
[2021-12-20 21:19:21] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2021-12-20 21:19:21] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2021-12-20 21:19:21] production.DEBUG: Nordigen token is valid until 2021-12-21 21:17:09  
[2021-12-20 21:19:21] production.DEBUG: Nordigen token is valid.  
[2021-12-20 21:19:21] production.DEBUG: Going to collect account information from Nordigen.  
[2021-12-20 21:19:21] production.DEBUG: Now generate transactions.  
[2021-12-20 21:19:21] production.DEBUG: Add message on index #0 (line no. 1): Parsed 0 Nordigen transactions for further processing.  
[2021-12-20 21:19:21] production.DEBUG: Now in storeConversionStatus(conv-3PAhLdLwEvVo): conv_running  
[2021-12-20 21:19:21] production.DEBUG: Done parsing transactions.  
[2021-12-20 21:19:21] production.DEBUG: Generated 0 Firefly III transactions.  
[2021-12-20 21:19:21] production.DEBUG: Add message on index #0 (line no. 1): Filtered down from 0 (possibly duplicate) entries to 0 unique transactions.  
[2021-12-20 21:19:21] production.DEBUG: Now in storeConversionStatus(conv-3PAhLdLwEvVo): conv_running  
[2021-12-20 21:19:21] production.DEBUG: Filtered down to 0 Firefly III transactions.  
[2021-12-20 21:19:21] production.ERROR: Zero transactions!  
[2021-12-20 21:19:21] production.DEBUG: Now in setConversionStatus(conv_errored)  
[2021-12-20 21:19:21] production.DEBUG: Found "conv-3PAhLdLwEvVo" in the session  
[2021-12-20 21:19:21] production.DEBUG: Now in startOrFindConversion(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:21] production.DEBUG: Try to see if file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:21] production.DEBUG: Status file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:21] production.DEBUG: Now in storeConversionStatus(conv-3PAhLdLwEvVo): conv_errored  
[2021-12-20 21:19:21] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:19:21] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:21] production.DEBUG: Now in startOrFindConversion(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:21] production.DEBUG: Try to see if file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:21] production.DEBUG: Status file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:21] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:19:21] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:21] production.DEBUG: Now in startOrFindConversion(conv-3PAhLdLwEvVo)  
[2021-12-20 21:19:21] production.DEBUG: Try to see if file exists for conversion "conv-3PAhLdLwEvVo".  
[2021-12-20 21:19:21] production.DEBUG: Status file exists for conversion "conv-3PAhLdLwEvVo".  

```

**Comment by Vercety87** [comment]
My bad, I just check the develop container, but I can’t see your change on the given.

So I get all the modified files from here https://github.com/firefly-iii/firefly-iii/issues/5407 and restarted my container.

Now in front of my bank accounts I can select my assets account, but after that I’m stuck in a loop on the next page :



```
Debug information generated at 2021-12-20 21:41:00 Europe/Amsterdam for Firefly III Data Importer version **0.4.0**.

| Scope | Version |
| --- | --- |
| FIDI | 0.4.0 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Paris |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15 |
```

```
Truncated from this point <----| to roles..  
[2021-12-20 21:40:50] production.DEBUG: NO mapping in file, will send you back to mapping..  
[2021-12-20 21:40:50] production.DEBUG: Conversion routine manager identifier is "conv-trW132FihDxQ"  
[2021-12-20 21:40:50] production.DEBUG: Stored "conv-trW132FihDxQ" under "conversion_job_id"  
[2021-12-20 21:40:50] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:50] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-trW132FihDxQ)  
[2021-12-20 21:40:50] production.DEBUG: Now in startOrFindConversion(conv-trW132FihDxQ)  
[2021-12-20 21:40:50] production.DEBUG: Try to see if file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:50] production.DEBUG: Status file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:53] production.DEBUG: isReadyForNordigenStep("map")  
[2021-12-20 21:40:53] production.DEBUG: Return false, not yet ready for step [2].  
[2021-12-20 21:40:53] production.DEBUG: redirectToCorrectNordigenStep("map")  
[2021-12-20 21:40:53] production.DEBUG: Is ready for conversion, so send to conversion.  
[2021-12-20 21:40:53] production.DEBUG: Return redirect to "http://192.168.0.80:8087/import/convert"  
[2021-12-20 21:40:53] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:53] production.DEBUG: Now in App\Http\Controllers\Import\ConversionController::index  
[2021-12-20 21:40:53] production.DEBUG: Will now verify configuration content.  
[2021-12-20 21:40:53] production.DEBUG: NO role info in config, will send you back to roles..  
[2021-12-20 21:40:53] production.DEBUG: NO mapping in file, will send you back to mapping..  
[2021-12-20 21:40:53] production.DEBUG: Conversion routine manager identifier is "conv-trW132FihDxQ"  
[2021-12-20 21:40:53] production.DEBUG: Stored "conv-trW132FihDxQ" under "conversion_job_id"  
[2021-12-20 21:40:53] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:53] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-trW132FihDxQ)  
[2021-12-20 21:40:53] production.DEBUG: Now in startOrFindConversion(conv-trW132FihDxQ)  
[2021-12-20 21:40:53] production.DEBUG: Try to see if file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:53] production.DEBUG: Status file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:56] production.DEBUG: isReadyForNordigenStep("map")  
[2021-12-20 21:40:56] production.DEBUG: Return false, not yet ready for step [2].  
[2021-12-20 21:40:56] production.DEBUG: redirectToCorrectNordigenStep("map")  
[2021-12-20 21:40:56] production.DEBUG: Is ready for conversion, so send to conversion.  
[2021-12-20 21:40:56] production.DEBUG: Return redirect to "http://192.168.0.80:8087/import/convert"  
[2021-12-20 21:40:56] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:56] production.DEBUG: Now in App\Http\Controllers\Import\ConversionController::index  
[2021-12-20 21:40:56] production.DEBUG: Will now verify configuration content.  
[2021-12-20 21:40:56] production.DEBUG: NO role info in config, will send you back to roles..  
[2021-12-20 21:40:56] production.DEBUG: NO mapping in file, will send you back to mapping..  
[2021-12-20 21:40:56] production.DEBUG: Conversion routine manager identifier is "conv-trW132FihDxQ"  
[2021-12-20 21:40:56] production.DEBUG: Stored "conv-trW132FihDxQ" under "conversion_job_id"  
[2021-12-20 21:40:56] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:56] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-trW132FihDxQ)  
[2021-12-20 21:40:56] production.DEBUG: Now in startOrFindConversion(conv-trW132FihDxQ)  
[2021-12-20 21:40:56] production.DEBUG: Try to see if file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:56] production.DEBUG: Status file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:58] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:58] production.DEBUG: Now in App\Http\Controllers\Import\ConversionController::index  
[2021-12-20 21:40:58] production.DEBUG: Will now verify configuration content.  
[2021-12-20 21:40:58] production.DEBUG: NO role info in config, will send you back to roles..  
[2021-12-20 21:40:58] production.DEBUG: NO mapping in file, will send you back to mapping..  
[2021-12-20 21:40:58] production.DEBUG: Conversion routine manager identifier is "conv-trW132FihDxQ"  
[2021-12-20 21:40:58] production.DEBUG: Stored "conv-trW132FihDxQ" under "conversion_job_id"  
[2021-12-20 21:40:58] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:58] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-trW132FihDxQ)  
[2021-12-20 21:40:58] production.DEBUG: Now in startOrFindConversion(conv-trW132FihDxQ)  
[2021-12-20 21:40:58] production.DEBUG: Try to see if file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:58] production.DEBUG: Status file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:59] production.DEBUG: isReadyForNordigenStep("map")  
[2021-12-20 21:40:59] production.DEBUG: Return false, not yet ready for step [2].  
[2021-12-20 21:40:59] production.DEBUG: redirectToCorrectNordigenStep("map")  
[2021-12-20 21:40:59] production.DEBUG: Is ready for conversion, so send to conversion.  
[2021-12-20 21:40:59] production.DEBUG: Return redirect to "http://192.168.0.80:8087/import/convert"  
[2021-12-20 21:40:59] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:59] production.DEBUG: Now in App\Http\Controllers\Import\ConversionController::index  
[2021-12-20 21:40:59] production.DEBUG: Will now verify configuration content.  
[2021-12-20 21:40:59] production.DEBUG: NO role info in config, will send you back to roles..  
[2021-12-20 21:40:59] production.DEBUG: NO mapping in file, will send you back to mapping..  
[2021-12-20 21:40:59] production.DEBUG: Conversion routine manager identifier is "conv-trW132FihDxQ"  
[2021-12-20 21:40:59] production.DEBUG: Stored "conv-trW132FihDxQ" under "conversion_job_id"  
[2021-12-20 21:40:59] production.DEBUG: isReadyForNordigenStep("conversion")  
[2021-12-20 21:40:59] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-trW132FihDxQ)  
[2021-12-20 21:40:59] production.DEBUG: Now in startOrFindConversion(conv-trW132FihDxQ)  
[2021-12-20 21:40:59] production.DEBUG: Try to see if file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:40:59] production.DEBUG: Status file exists for conversion "conv-trW132FihDxQ".  
[2021-12-20 21:41:00] production.DEBUG: Now at App\Http\Controllers\IndexController::index  
[2021-12-20 21:41:00] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2021-12-20 21:41:00] production.DEBUG: Now at App\Http\Controllers\TokenController::doValidate  
[2021-12-20 21:41:00] production.DEBUG: isReadyForNordigenStep("service-validation")  
[2021-12-20 21:41:00] production.DEBUG: isReadyForNordigenStep("service-validation")  
[2021-12-20 21:41:00] production.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate  
[2021-12-20 21:41:00] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2021-12-20 21:41:00] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.  
[2021-12-20 21:41:00] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.  
[2021-12-20 21:41:00] production.DEBUG: No Nordigen ID in hasId(), will return config variable.  
[2021-12-20 21:41:00] production.DEBUG: setParameters  
[2021-12-20 21:41:00] production.DEBUG: No Nordigen key in hasKey(), will return config variable.  
[2021-12-20 21:41:00] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2021-12-20 21:41:00] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2021-12-20 21:41:00] production.DEBUG: Nordigen token is valid until 2021-12-21 21:39:09  
[2021-12-20 21:41:00] production.DEBUG: Nordigen token is valid.  

```

**Comment by JC5** [comment]
Nice loop! I'll pick it up. Thanks for debugging! :+1:

**Comment by JC5** [comment]
OK, I can't find the issue directly, unfortunately, so I've added some extra debug information to the logging. If you could pull the latest `develop` Docker image, you should be able to see this information.

You can recognize the latest Docker build because (at the time of writing) the build number on the `/debug` page should be **34 or higher**.

I would appreciate the full logs, which you can retrieve using `docker logs [CONTAINER] > logfiles.log` on the command line. Since they will contain sensitive information, please send them to james@firefly-iii.org

Sorry for putting you through so much trouble!

**Comment by Vercety87** [comment]
Hi,

No loop with the latest version. I got some errors with the import but looks ok. I sended you the log file.

**Comment by JC5** [comment]
Thanks! I'll check it out, and see if there's anything that still needs fixing. Otherwise, I'll mark this as fixed.

**Comment by JC5** [comment]
I see the errors and I will pick them up. You can delete the message, I've saved the error from your logs but nothing else.

Thanks for the hard work, appreciate it!
