### ISSUE TITLE
Cannot declare class __CreatePersonalAccessTokensTable | firefly 5.6.15

### ISSUE THREAD

**Issue by GaneshKandu** [firefly-iii/firefly-iii#5833]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am getting an issue while install of firefly 5.6.15

```php artisan migrate:refresh --seed
Migration table not found.
Migration table created successfully.
PHP Fatal error:  Cannot declare class CreatePersonalAccessTokensTable, because the name is already in use in database/migrations/2021_12_27_000001_create_personal_access_tokens_table.php on line 11

In 2021_12_27_000001_create_personal_access_tokens_table.php line 11:

Cannot declare class CreatePersonalAccessTokensTable, because the name is already in use
```

Following this steps [Installing Firefly III](https://docs.firefly-iii.org/firefly-iii/installation/self_hosted/#ingredients) and getting error on ```php artisan migrate:refresh --seed``` command.

### Expected behaviour

it should be completed successfully.

### Debug information

its because no table were created only migration table created.
```[FireflyIII](http://w2.nuftp.com/manual/firefly5615/public)
Whoops! An error occurred.

Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Could not poll the database: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'firefly5615.configuration' doesn't exist (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)
More information

Please collect more information in the storage/logs directory where you will find log files. If you're running Docker, use docker logs -f [container]. You can read more about collecting error information in [the FAQ](https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode).
Get help [on GitHub](https://github.com/firefly-iii/firefly-iii/issues)

You're more than welcome to open a new issue on GitHub.

    Use the search!
    Include the information [from this debug page](http://w2.nuftp.com/manual/firefly5615/public/debug).
    Tell us more than "it says Whoops!"
    Include error logs (see above).
    Tell us what you were doing.
```

### Steps to reproduce

1. composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly5614 5.6.15
2. sudo chown -R www-data:www-data firefly-iii
3. sudo chmod -R 775 firefly-iii/storage
4. Fill up details in .env
5. php artisan key:generate
6. php artisan migrate:refresh --seed

### Additional info

```CreatePersonalAccessTokensTable``` is declared in these two files

database\migrations\2021_12_27_000001_create_personal_access_tokens_table.php on Line 11

https://github.com/firefly-iii/firefly-iii/blob/a8cbbde8fcaef5bf0027305ad08a51ece45ab24b/database/migrations/2021_12_27_000001_create_personal_access_tokens_table.php#L8-L14

vendor\laravel\sanctum\database\migrations\2019_12_14_000001_create_personal_access_tokens_table.php on Line 7

https://github.com/laravel/sanctum/blob/f4f77b177923e74dde29e85bc0bb2e18527fd557/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php#L3-L11

I think ```vendor\laravel\sanctum\database\migrations\2019_12_14_000001_create_personal_access_tokens_table.php``` file getting loaded twice. but ```database\migrations\2021_12_27_000001_create_personal_access_tokens_table.php``` added recently.

when i am changing class name class name in error changing with similar name.

**Comment by JC5** [comment]
I see what you mean, thanks for letting me know. I'll release a fix soon.

**Comment by JC5** [comment]
This should be fixed in 5.6.16

**Comment by GaneshKandu** [comment]
Thanks @JC5 !

**Comment by yannik-b** [comment]
Have the same problem still - when can I expect 5.6.16 on Docker Hub?

**Comment by JC5** [comment]
Should be up any minute.

**Comment by yannik-b** [comment]
Thank you very much :)
