### ISSUE TITLE
advance payment tags are broken

### ISSUE THREAD

**Issue by worldworm** [firefly-iii/firefly-iii#614]
I think the tagging system is broken (or i didn't get it)
I created a new advance payment tag. Then I added a withdrawal with this tag. Everything works here.
But when i create a deposit to repay that expense, the tag disappers after saving (not the tag, only the connection to this deposit)

**Comment by JC5** [comment]
Fixed! Do a git pull and you should be good.

Problem was caused by a sloppy copy/paste action by me.

**Comment by worldworm** [comment]
Great, it works.
Thanks!

**Comment by worldworm** [comment]
Hey there, 
updatet to Version 4.3.7 today. Tags are working like a charm, big thanks!

Only want to inform you, that this problem (above) is still happening on the old tag, expense, withdrawal (the tags and transactions where i discovered this problem on (created in the old version where the bug happened)).
When you create a new tag AND transactions it is working.

For me it isn't a problem (so no stress here :) ), i created everything new. I only want to let you know it, so you can decide if it needs a closer look

**Comment by JC5** [comment]
It is possible that this is cache related, but I will look into the issue. The "calculation" is live but parts of it may be cached.

You could run `php artisan cache:clear` to see what happens.

Thanks for pointing this out 👍 ±
