### ISSUE TITLE
2FA QR Code invalid

### ISSUE THREAD

**Issue by Squirrel3000** [firefly-iii/firefly-iii#624]
When I try to enable 2FA it says the QR Code is invalid. Tried with both Authy and Google Authenticator.

Phone is an iPhone SE.

**Comment by JC5** [comment]
So you do get a generated QR code, but both apps say the QR code is invalid?

Could you share the QR code here? It might be missing info for some reason.

Also, can you share which version of Firefly you're running?

**Comment by TheSerenin** [comment]
QR Code is as follows: http://prntscr.com/eo8n19

I'm running Firefly 4.3.7 on PHP 7.1.3

**Comment by JC5** [comment]
I think so yes, because I was able to scan your QR code, and add it to my Authenticator app. This is on a Android phone though. I removed it from your post so others won't see it in the future.

Is the time on your phone correct? And on your server as well?

**Comment by TheSerenin** [comment]
The time on my phone and server are both correct. I'm guessing it has something to do with the way iOS processes QR? Not sure.

**Comment by JC5** [comment]
Mmm, I would have to experiment. I can't imagine these two systems to be radically different: surely you and I would not be the only ones who suffered from this issue.

The only thing I can find online is the need for "location services" to be on so the time on your phone is corrected / exact.

**Comment by TheSerenin** [comment]
Location Services are on.

**Comment by JC5** [comment]
I've been searching for solutions but nothing yet. Did you find anything yourself?

**Comment by coencoppens** [comment]
I'm afraid this issue should be reopened, since I think I'm experiencing the same thing.

Here's what I did:
* Enabled 2-step verification in Preferences > Security
* Firefly presented me the following QR-code:
![image](https://cloud.githubusercontent.com/assets/2962964/24570806/e1d741b6-166d-11e7-9f95-ab038f193b16.png)
* I tried to scan it on my iPhone using the [Google Authenticator app](https://itunes.apple.com/nl/app/google-authenticator/id388497605?mt=8), but that threw this error:
![error-authenticator](https://cloud.githubusercontent.com/assets/2962964/24571005/e7a4bafa-166e-11e7-81f5-61ac220265fa.jpg)

Some details:
* Firefly 4.3.7
* iPhone7 plus, running iOS 10.2.1

If you need more info, feel free to contact me :-)

**Comment by JC5** [comment]
I think I have an idea what causes this. Issue reopened!

**Comment by JC5** [comment]
OK guys, @TheSerenin and @coencoppens, open the following file:

[app/Http/Controllers/PreferencesController.php](https://github.com/firefly-iii/firefly-iii/blob/master/app/Http/Controllers/PreferencesController.php#L59)

Go to line 59, which should say something with "generateSecretKey".

Change the `32` into `16`.

Then, retry!

**Comment by JC5** [comment]
I've updated the instructions above. It's no longer about replacing a number, but replacing the entire line.

**Comment by coencoppens** [comment]
@JC5, I've changed the line but it doesn't resolve the issue unfortunately. The error message is the same as the one I posted earlier, only the value of the secret has changed.

*Ping @TheSerenin *

**Comment by JC5** [comment]
Could you try another app, like Authy?

**Comment by coencoppens** [comment]
Nope, sorry..
![430521364_13100506598311237096](https://cloud.githubusercontent.com/assets/2962964/24578948/6c635620-16ec-11e7-9083-0f8f58e3f72d.jpg)

**Comment by JC5** [comment]
Could you share the QR code?

**Comment by coencoppens** [comment]
Assuming it's always the same code:
![](http://i.imgur.com/43OCiYP.jpg)

**Comment by JC5** [comment]
Alright, the code works perfectly for me. So it's some kind of iOS issue. I'll have to dig further.

**Comment by melvinchia** [comment]
To add on from my referenced issue, this isn't a QR code issue, but seems to be an issue with the secret key. I've tested with and without prefix, scanning in the QR code, or manually (painfully) keying in the secret, albeit only doing it on Authy on iOS.

When I tried using no prefix:
$otp_secret = $google2fa->generateSecretKey(16);
It generates a usable secret, tested by Authy on iOS (manually key in the secret, or QR code scan)

When I tried using a blank prefix:
$otp_secret = $google2fa->generateSecretKey(16, '');
It generates a usable secret, tested by Authy on iOS (manually key in the secret, or QR code scan)

When I add a prefix prefix:
$otp_secret = $google2fa->generateSecretKey(16, 'm');
$otp_secret = $google2fa->generateSecretKey(16, 'mel');
$otp_secret = $google2fa->generateSecretKey(16, 'melvin');
All 3 lines yield an error, whether manually keying in the secret, or QR code scan.

**Comment by JC5** [comment]
This could be because the length (16) plus the length of the prefix in base32 is not a power of 2. I was under the impression my own combination (16 + 'FIREFLYIII') was, but I might have been wrong. The new code, as committed by @antonioribeiro catches this so it might be something else.

**Comment by antonioribeiro** [comment]
To be compatible with Google Authenticator, the length of the secret key must have at least 8 chars and be a power of 2, so you can do something like this in your code:

    $secretKey = '123456789';

    $secretKey = str_pad($secretKey, pow(2,ceil(log(strlen($secretKey),2))), 'X');

To get 

    123456789XXXXXXX

**Comment by antonioribeiro** [comment]
Just wrote something more about it in the docs: https://github.com/antonioribeiro/google2fa#google-authenticator-secret-key-compatibility

**Comment by JC5** [comment]
That is a very good idea! I appreciate your clarification. @coencoppens , I've updated the code (see the files I linked to before) and I invite you to try it.

**Comment by melvinchia** [comment]
@antonioribeiro , just to clarify, the purpose of the following (sub)function:

$secretKey = $google2fa->generateSecretKey(16, $userId);

Was documented as "prefixing the secret key", whereby a $userId is provided to the function, which would use the $userId to prefix the salt to generate a 16-bit key. Similarly if 32 is used, the purpose of the $userId is to prefix the salt to generate the key.

Now the explanation seems to be that I have to provide a 16/32-character (padded or full length) $userId which becomes the salt, instead of merely being just a prefix (original intention to increase security)? Am I understanding the explanation wrong here?

**Comment by coencoppens** [comment]
@JC5 TL;DR: upgraded to 4.3.8 but it still doesn't work.

Thanks for the updated code and the [easy upgrade instructions](https://firefly-iii.github.io/using-upgrading.html), this is what I call easy upgrading!

Since it's a bug you're having a hard time testing (which I assume seeing you have to release the code before it can be tested), maybe I can help you out by using a feature branch to test on? I'd be happy to help you by installing it alongside the production version. If you think there's another way of me helping, please let me know - I think it's the least I can do (besides donating ;)) to show my appreciation for your work.

**Comment by JC5** [comment]
Hi Coen! I'm glad it worked out!

I have a hard time testing this indeed. You could donate a new iPhone? ;).

Your help would most welcome. If you create a pull request, Github will give you your very own branch, which I in turn can commit to as well. At least, I believe I can. And if not, I can comment.

Currently I'm torn whether or not using a prefix at all is necessary (worth the trouble). I would like to ask you to see if you can find a working combination of a static prefix and the length of the key (ie. 16, 32, 31?).

Then, the next step would be to find a way to use a _dynamic_ prefix, such as the user's email address.

**Comment by coencoppens** [comment]
@JC5 , shouldn't I just clone a development branch of yours? That way you can develop as normal, and I can test it?

**Comment by JC5** [comment]
Sorry, I haven't taken the time to look at this. I decided to remove the prefix. The new version, 4.4.3, should be live in about 1hr. Let me know if the codes work!

**Comment by coencoppens** [comment]
Going to take it for a test drive :-)

**Comment by JC5** [comment]
Without any prefix it should be back to the original functionality. I'm not sure what else to do. But I'll keep on the look-out for another library.

**Comment by pztrn** [comment]
Hey guys, sorry for bumping, but I've managed to get 2FA working with FreeOTP and by making generateSecretKey line looks like this:

```
$secret = $google2fa->generateSecretKey();
```

Maybe it helps someone.

And yes, **check time on your phone, there must be no clock skews!**

**Comment by JC5** [comment]
That's alright!

The code in FF3 is now back to the original settings. I have no idea what else might work.
