### ISSUE TITLE
"Your accounts" graph shows changes at wrong dates

### ISSUE THREAD

**Issue by SteffoSpieler** [firefly-iii/firefly-iii#9752]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Since v6.2.0 the "Your accounts" graph shows changes at the wrong dates.
I was able to reproduce this on https://demo.firefly-iii.org/ and I think an image could describe it a bit better:

![Image](https://github.com/user-attachments/assets/64d32c40-40f0-451e-a808-21eb7d9b262b)

(`1.` and `3.` are the date that the transactions actually happened on.)

### Debug information

Debug information generated at 2025-02-03 09:23:21 for Firefly III version **v6.2.2**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.2.2 / <span>#</span>25 (expects <span>#</span>25)</td></tr><tr><td>PHP version</td><td>8.4.3 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>104857600 (100 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Berlin + Europe/Berlin</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver, session driver</td><td>file, file</td></tr><tr><td>Default language and locale</td><td>de_DE + equal</td></tr><tr><td>Trusted proxies</td><td><code>**</code></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2025-02-02 23:00:00 (9 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr><tr><td>Exchange rates</td><td>Disabled, downloads disabled</td></tr><tr><td>RB-column</td><td>Disabled</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has reconciled">:ledger:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Native currency</td><td>EUR</td></tr><tr><td>Convert to native currency?</td><td>Disabled</td></tr><tr><td>Session start</td><td>2025-02-01 00:00:00</td></tr><tr><td>Session end</td><td>2025-02-28 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>de_DE</td></tr><tr><td>User locale</td><td>de_DE</td></tr><tr><td>Locale(s) supported</td><td>de_DE.utf8: :white_check_mark:<br>de_DE.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0</td></tr></tbody></table>

### Expected behaviour

I'd expect to see account value changes on the date they actually happened on.

### Steps to reproduce

1. Have (multiple) transactions.
2. See error.

**Comment by JC5** [comment]
Hey, thanks for opening an issue!

https://github.com/orgs/firefly-iii/discussions/9727

I found out yesterday, thanks! I had no issue yet, but the problem is fixed in the develop branch. It should go live soon.

Cheers, James

**Comment by SteffoSpieler** [comment]
This issue is still happening on the latest Version (6.2.4), as well as on the current demo site ("Version develop/2025-02-05").
